// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _DeviceCommStateRsp.proto

package mina2.jp_tcp.proto;

public final class DeviceCommStateRsp {
  private DeviceCommStateRsp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DeviceCommStateListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeviceCommStateList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
     */
    java.util.List<DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem> 
        getDcItemList();
    /**
     * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
     */
    DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem getDcItem(int index);
    /**
     * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
     */
    int getDcItemCount();
    /**
     * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
     */
    java.util.List<? extends DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItemOrBuilder> 
        getDcItemOrBuilderList();
    /**
     * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
     */
    DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItemOrBuilder getDcItemOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DeviceCommStateList}
   */
  public static final class DeviceCommStateList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DeviceCommStateList)
      DeviceCommStateListOrBuilder {
    // Use DeviceCommStateList.newBuilder() to construct.
    private DeviceCommStateList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeviceCommStateList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeviceCommStateList defaultInstance;
    public static DeviceCommStateList getDefaultInstance() {
      return defaultInstance;
    }

    public DeviceCommStateList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceCommStateList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                dcItem_ = new java.util.ArrayList<DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              dcItem_.add(input.readMessage(DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          dcItem_ = java.util.Collections.unmodifiableList(dcItem_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DeviceCommStateRsp.internal_static_Proto_DeviceCommStateList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DeviceCommStateRsp.internal_static_Proto_DeviceCommStateList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DeviceCommStateRsp.DeviceCommStateList.class, DeviceCommStateRsp.DeviceCommStateList.Builder.class);
    }

    public static com.google.protobuf.Parser<DeviceCommStateList> PARSER =
        new com.google.protobuf.AbstractParser<DeviceCommStateList>() {
      public DeviceCommStateList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceCommStateList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceCommStateList> getParserForType() {
      return PARSER;
    }

    public interface DeviceCommStateItemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:DeviceCommStateList.DeviceCommStateItem)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required int64 id = 1;</code>
       */
      boolean hasId();
      /**
       * <code>required int64 id = 1;</code>
       */
      long getId();

      /**
       * <code>optional int64 devid = 2;</code>
       */
      boolean hasDevid();
      /**
       * <code>optional int64 devid = 2;</code>
       */
      long getDevid();

      /**
       * <code>optional bytes attid = 3;</code>
       */
      boolean hasAttid();
      /**
       * <code>optional bytes attid = 3;</code>
       */
      com.google.protobuf.ByteString getAttid();

      /**
       * <code>optional bytes attcode = 4;</code>
       *
       * <pre>
       *�豸���Ա���
       * </pre>
       */
      boolean hasAttcode();
      /**
       * <code>optional bytes attcode = 4;</code>
       *
       * <pre>
       *�豸���Ա���
       * </pre>
       */
      com.google.protobuf.ByteString getAttcode();

      /**
       * <code>required float fvalue = 5;</code>
       */
      boolean hasFvalue();
      /**
       * <code>required float fvalue = 5;</code>
       */
      float getFvalue();

      /**
       * <code>required bytes commstate = 6;</code>
       */
      boolean hasCommstate();
      /**
       * <code>required bytes commstate = 6;</code>
       */
      com.google.protobuf.ByteString getCommstate();

      /**
       * <code>optional bytes commcontent = 7;</code>
       */
      boolean hasCommcontent();
      /**
       * <code>optional bytes commcontent = 7;</code>
       */
      com.google.protobuf.ByteString getCommcontent();
    }
    /**
     * Protobuf type {@code DeviceCommStateList.DeviceCommStateItem}
     */
    public static final class DeviceCommStateItem extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:DeviceCommStateList.DeviceCommStateItem)
        DeviceCommStateItemOrBuilder {
      // Use DeviceCommStateItem.newBuilder() to construct.
      private DeviceCommStateItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private DeviceCommStateItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final DeviceCommStateItem defaultInstance;
      public static DeviceCommStateItem getDefaultInstance() {
        return defaultInstance;
      }

      public DeviceCommStateItem getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private DeviceCommStateItem(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt64();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                devid_ = input.readInt64();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                attid_ = input.readBytes();
                break;
              }
              case 34: {
                bitField0_ |= 0x00000008;
                attcode_ = input.readBytes();
                break;
              }
              case 45: {
                bitField0_ |= 0x00000010;
                fvalue_ = input.readFloat();
                break;
              }
              case 50: {
                bitField0_ |= 0x00000020;
                commstate_ = input.readBytes();
                break;
              }
              case 58: {
                bitField0_ |= 0x00000040;
                commcontent_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DeviceCommStateRsp.internal_static_Proto_DeviceCommStateList_DeviceCommStateItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DeviceCommStateRsp.internal_static_Proto_DeviceCommStateList_DeviceCommStateItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.class, DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.Builder.class);
      }

      public static com.google.protobuf.Parser<DeviceCommStateItem> PARSER =
          new com.google.protobuf.AbstractParser<DeviceCommStateItem>() {
        public DeviceCommStateItem parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DeviceCommStateItem(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<DeviceCommStateItem> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private long id_;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }

      public static final int DEVID_FIELD_NUMBER = 2;
      private long devid_;
      /**
       * <code>optional int64 devid = 2;</code>
       */
      public boolean hasDevid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 devid = 2;</code>
       */
      public long getDevid() {
        return devid_;
      }

      public static final int ATTID_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString attid_;
      /**
       * <code>optional bytes attid = 3;</code>
       */
      public boolean hasAttid() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes attid = 3;</code>
       */
      public com.google.protobuf.ByteString getAttid() {
        return attid_;
      }

      public static final int ATTCODE_FIELD_NUMBER = 4;
      private com.google.protobuf.ByteString attcode_;
      /**
       * <code>optional bytes attcode = 4;</code>
       *
       * <pre>
       *�豸���Ա���
       * </pre>
       */
      public boolean hasAttcode() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes attcode = 4;</code>
       *
       * <pre>
       *�豸���Ա���
       * </pre>
       */
      public com.google.protobuf.ByteString getAttcode() {
        return attcode_;
      }

      public static final int FVALUE_FIELD_NUMBER = 5;
      private float fvalue_;
      /**
       * <code>required float fvalue = 5;</code>
       */
      public boolean hasFvalue() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required float fvalue = 5;</code>
       */
      public float getFvalue() {
        return fvalue_;
      }

      public static final int COMMSTATE_FIELD_NUMBER = 6;
      private com.google.protobuf.ByteString commstate_;
      /**
       * <code>required bytes commstate = 6;</code>
       */
      public boolean hasCommstate() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required bytes commstate = 6;</code>
       */
      public com.google.protobuf.ByteString getCommstate() {
        return commstate_;
      }

      public static final int COMMCONTENT_FIELD_NUMBER = 7;
      private com.google.protobuf.ByteString commcontent_;
      /**
       * <code>optional bytes commcontent = 7;</code>
       */
      public boolean hasCommcontent() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes commcontent = 7;</code>
       */
      public com.google.protobuf.ByteString getCommcontent() {
        return commcontent_;
      }

      private void initFields() {
        id_ = 0L;
        devid_ = 0L;
        attid_ = com.google.protobuf.ByteString.EMPTY;
        attcode_ = com.google.protobuf.ByteString.EMPTY;
        fvalue_ = 0F;
        commstate_ = com.google.protobuf.ByteString.EMPTY;
        commcontent_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasFvalue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasCommstate()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt64(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, devid_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, attid_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeBytes(4, attcode_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeFloat(5, fvalue_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeBytes(6, commstate_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeBytes(7, commcontent_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, devid_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, attid_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(4, attcode_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(5, fvalue_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(6, commstate_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(7, commcontent_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code DeviceCommStateList.DeviceCommStateItem}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:DeviceCommStateList.DeviceCommStateItem)
          DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return DeviceCommStateRsp.internal_static_Proto_DeviceCommStateList_DeviceCommStateItem_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return DeviceCommStateRsp.internal_static_Proto_DeviceCommStateList_DeviceCommStateItem_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.class, DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.Builder.class);
        }

        // Construct using DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          devid_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          attid_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          attcode_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000008);
          fvalue_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000010);
          commstate_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000020);
          commcontent_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000040);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return DeviceCommStateRsp.internal_static_Proto_DeviceCommStateList_DeviceCommStateItem_descriptor;
        }

        public DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem getDefaultInstanceForType() {
          return DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.getDefaultInstance();
        }

        public DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem build() {
          DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem buildPartial() {
          DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem result = new DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.devid_ = devid_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.attid_ = attid_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.attcode_ = attcode_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.fvalue_ = fvalue_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.commstate_ = commstate_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.commcontent_ = commcontent_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem) {
            return mergeFrom((DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem other) {
          if (other == DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasDevid()) {
            setDevid(other.getDevid());
          }
          if (other.hasAttid()) {
            setAttid(other.getAttid());
          }
          if (other.hasAttcode()) {
            setAttcode(other.getAttcode());
          }
          if (other.hasFvalue()) {
            setFvalue(other.getFvalue());
          }
          if (other.hasCommstate()) {
            setCommstate(other.getCommstate());
          }
          if (other.hasCommcontent()) {
            setCommcontent(other.getCommcontent());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasFvalue()) {
            
            return false;
          }
          if (!hasCommstate()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private long id_ ;
        /**
         * <code>required int64 id = 1;</code>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required int64 id = 1;</code>
         */
        public long getId() {
          return id_;
        }
        /**
         * <code>required int64 id = 1;</code>
         */
        public Builder setId(long value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 id = 1;</code>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0L;
          onChanged();
          return this;
        }

        private long devid_ ;
        /**
         * <code>optional int64 devid = 2;</code>
         */
        public boolean hasDevid() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int64 devid = 2;</code>
         */
        public long getDevid() {
          return devid_;
        }
        /**
         * <code>optional int64 devid = 2;</code>
         */
        public Builder setDevid(long value) {
          bitField0_ |= 0x00000002;
          devid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 devid = 2;</code>
         */
        public Builder clearDevid() {
          bitField0_ = (bitField0_ & ~0x00000002);
          devid_ = 0L;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString attid_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes attid = 3;</code>
         */
        public boolean hasAttid() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional bytes attid = 3;</code>
         */
        public com.google.protobuf.ByteString getAttid() {
          return attid_;
        }
        /**
         * <code>optional bytes attid = 3;</code>
         */
        public Builder setAttid(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          attid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes attid = 3;</code>
         */
        public Builder clearAttid() {
          bitField0_ = (bitField0_ & ~0x00000004);
          attid_ = getDefaultInstance().getAttid();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString attcode_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes attcode = 4;</code>
         *
         * <pre>
         *�豸���Ա���
         * </pre>
         */
        public boolean hasAttcode() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional bytes attcode = 4;</code>
         *
         * <pre>
         *�豸���Ա���
         * </pre>
         */
        public com.google.protobuf.ByteString getAttcode() {
          return attcode_;
        }
        /**
         * <code>optional bytes attcode = 4;</code>
         *
         * <pre>
         *�豸���Ա���
         * </pre>
         */
        public Builder setAttcode(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
          attcode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes attcode = 4;</code>
         *
         * <pre>
         *�豸���Ա���
         * </pre>
         */
        public Builder clearAttcode() {
          bitField0_ = (bitField0_ & ~0x00000008);
          attcode_ = getDefaultInstance().getAttcode();
          onChanged();
          return this;
        }

        private float fvalue_ ;
        /**
         * <code>required float fvalue = 5;</code>
         */
        public boolean hasFvalue() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required float fvalue = 5;</code>
         */
        public float getFvalue() {
          return fvalue_;
        }
        /**
         * <code>required float fvalue = 5;</code>
         */
        public Builder setFvalue(float value) {
          bitField0_ |= 0x00000010;
          fvalue_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required float fvalue = 5;</code>
         */
        public Builder clearFvalue() {
          bitField0_ = (bitField0_ & ~0x00000010);
          fvalue_ = 0F;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString commstate_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes commstate = 6;</code>
         */
        public boolean hasCommstate() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>required bytes commstate = 6;</code>
         */
        public com.google.protobuf.ByteString getCommstate() {
          return commstate_;
        }
        /**
         * <code>required bytes commstate = 6;</code>
         */
        public Builder setCommstate(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
          commstate_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes commstate = 6;</code>
         */
        public Builder clearCommstate() {
          bitField0_ = (bitField0_ & ~0x00000020);
          commstate_ = getDefaultInstance().getCommstate();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString commcontent_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes commcontent = 7;</code>
         */
        public boolean hasCommcontent() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional bytes commcontent = 7;</code>
         */
        public com.google.protobuf.ByteString getCommcontent() {
          return commcontent_;
        }
        /**
         * <code>optional bytes commcontent = 7;</code>
         */
        public Builder setCommcontent(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          commcontent_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes commcontent = 7;</code>
         */
        public Builder clearCommcontent() {
          bitField0_ = (bitField0_ & ~0x00000040);
          commcontent_ = getDefaultInstance().getCommcontent();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:DeviceCommStateList.DeviceCommStateItem)
      }

      static {
        defaultInstance = new DeviceCommStateItem(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:DeviceCommStateList.DeviceCommStateItem)
    }

    public static final int DCITEM_FIELD_NUMBER = 1;
    private java.util.List<DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem> dcItem_;
    /**
     * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
     */
    public java.util.List<DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem> getDcItemList() {
      return dcItem_;
    }
    /**
     * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
     */
    public java.util.List<? extends DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItemOrBuilder> 
        getDcItemOrBuilderList() {
      return dcItem_;
    }
    /**
     * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
     */
    public int getDcItemCount() {
      return dcItem_.size();
    }
    /**
     * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
     */
    public DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem getDcItem(int index) {
      return dcItem_.get(index);
    }
    /**
     * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
     */
    public DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItemOrBuilder getDcItemOrBuilder(
        int index) {
      return dcItem_.get(index);
    }

    private void initFields() {
      dcItem_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getDcItemCount(); i++) {
        if (!getDcItem(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < dcItem_.size(); i++) {
        output.writeMessage(1, dcItem_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dcItem_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dcItem_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DeviceCommStateRsp.DeviceCommStateList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceCommStateRsp.DeviceCommStateList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceCommStateRsp.DeviceCommStateList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceCommStateRsp.DeviceCommStateList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceCommStateRsp.DeviceCommStateList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeviceCommStateRsp.DeviceCommStateList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DeviceCommStateRsp.DeviceCommStateList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DeviceCommStateRsp.DeviceCommStateList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DeviceCommStateRsp.DeviceCommStateList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeviceCommStateRsp.DeviceCommStateList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DeviceCommStateRsp.DeviceCommStateList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DeviceCommStateList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeviceCommStateList)
        DeviceCommStateRsp.DeviceCommStateListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DeviceCommStateRsp.internal_static_Proto_DeviceCommStateList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DeviceCommStateRsp.internal_static_Proto_DeviceCommStateList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DeviceCommStateRsp.DeviceCommStateList.class, DeviceCommStateRsp.DeviceCommStateList.Builder.class);
      }

      // Construct using DeviceCommStateRsp.DeviceCommStateList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDcItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (dcItemBuilder_ == null) {
          dcItem_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dcItemBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DeviceCommStateRsp.internal_static_Proto_DeviceCommStateList_descriptor;
      }

      public DeviceCommStateRsp.DeviceCommStateList getDefaultInstanceForType() {
        return DeviceCommStateRsp.DeviceCommStateList.getDefaultInstance();
      }

      public DeviceCommStateRsp.DeviceCommStateList build() {
        DeviceCommStateRsp.DeviceCommStateList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DeviceCommStateRsp.DeviceCommStateList buildPartial() {
        DeviceCommStateRsp.DeviceCommStateList result = new DeviceCommStateRsp.DeviceCommStateList(this);
        int from_bitField0_ = bitField0_;
        if (dcItemBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            dcItem_ = java.util.Collections.unmodifiableList(dcItem_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dcItem_ = dcItem_;
        } else {
          result.dcItem_ = dcItemBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DeviceCommStateRsp.DeviceCommStateList) {
          return mergeFrom((DeviceCommStateRsp.DeviceCommStateList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DeviceCommStateRsp.DeviceCommStateList other) {
        if (other == DeviceCommStateRsp.DeviceCommStateList.getDefaultInstance()) return this;
        if (dcItemBuilder_ == null) {
          if (!other.dcItem_.isEmpty()) {
            if (dcItem_.isEmpty()) {
              dcItem_ = other.dcItem_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDcItemIsMutable();
              dcItem_.addAll(other.dcItem_);
            }
            onChanged();
          }
        } else {
          if (!other.dcItem_.isEmpty()) {
            if (dcItemBuilder_.isEmpty()) {
              dcItemBuilder_.dispose();
              dcItemBuilder_ = null;
              dcItem_ = other.dcItem_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dcItemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDcItemFieldBuilder() : null;
            } else {
              dcItemBuilder_.addAllMessages(other.dcItem_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDcItemCount(); i++) {
          if (!getDcItem(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DeviceCommStateRsp.DeviceCommStateList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DeviceCommStateRsp.DeviceCommStateList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem> dcItem_ =
        java.util.Collections.emptyList();
      private void ensureDcItemIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dcItem_ = new java.util.ArrayList<DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem>(dcItem_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem, DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.Builder, DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItemOrBuilder> dcItemBuilder_;

      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public java.util.List<DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem> getDcItemList() {
        if (dcItemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dcItem_);
        } else {
          return dcItemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public int getDcItemCount() {
        if (dcItemBuilder_ == null) {
          return dcItem_.size();
        } else {
          return dcItemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem getDcItem(int index) {
        if (dcItemBuilder_ == null) {
          return dcItem_.get(index);
        } else {
          return dcItemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public Builder setDcItem(
          int index, DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem value) {
        if (dcItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDcItemIsMutable();
          dcItem_.set(index, value);
          onChanged();
        } else {
          dcItemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public Builder setDcItem(
          int index, DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.Builder builderForValue) {
        if (dcItemBuilder_ == null) {
          ensureDcItemIsMutable();
          dcItem_.set(index, builderForValue.build());
          onChanged();
        } else {
          dcItemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public Builder addDcItem(DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem value) {
        if (dcItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDcItemIsMutable();
          dcItem_.add(value);
          onChanged();
        } else {
          dcItemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public Builder addDcItem(
          int index, DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem value) {
        if (dcItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDcItemIsMutable();
          dcItem_.add(index, value);
          onChanged();
        } else {
          dcItemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public Builder addDcItem(
          DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.Builder builderForValue) {
        if (dcItemBuilder_ == null) {
          ensureDcItemIsMutable();
          dcItem_.add(builderForValue.build());
          onChanged();
        } else {
          dcItemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public Builder addDcItem(
          int index, DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.Builder builderForValue) {
        if (dcItemBuilder_ == null) {
          ensureDcItemIsMutable();
          dcItem_.add(index, builderForValue.build());
          onChanged();
        } else {
          dcItemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public Builder addAllDcItem(
          java.lang.Iterable<? extends DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem> values) {
        if (dcItemBuilder_ == null) {
          ensureDcItemIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dcItem_);
          onChanged();
        } else {
          dcItemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public Builder clearDcItem() {
        if (dcItemBuilder_ == null) {
          dcItem_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dcItemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public Builder removeDcItem(int index) {
        if (dcItemBuilder_ == null) {
          ensureDcItemIsMutable();
          dcItem_.remove(index);
          onChanged();
        } else {
          dcItemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.Builder getDcItemBuilder(
          int index) {
        return getDcItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItemOrBuilder getDcItemOrBuilder(
          int index) {
        if (dcItemBuilder_ == null) {
          return dcItem_.get(index);  } else {
          return dcItemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public java.util.List<? extends DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItemOrBuilder> 
           getDcItemOrBuilderList() {
        if (dcItemBuilder_ != null) {
          return dcItemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dcItem_);
        }
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.Builder addDcItemBuilder() {
        return getDcItemFieldBuilder().addBuilder(
            DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.getDefaultInstance());
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.Builder addDcItemBuilder(
          int index) {
        return getDcItemFieldBuilder().addBuilder(
            index, DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.getDefaultInstance());
      }
      /**
       * <code>repeated .DeviceCommStateList.DeviceCommStateItem dcItem = 1;</code>
       */
      public java.util.List<DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.Builder> 
           getDcItemBuilderList() {
        return getDcItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem, DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.Builder, DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItemOrBuilder> 
          getDcItemFieldBuilder() {
        if (dcItemBuilder_ == null) {
          dcItemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem, DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItem.Builder, DeviceCommStateRsp.DeviceCommStateList.DeviceCommStateItemOrBuilder>(
                  dcItem_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          dcItem_ = null;
        }
        return dcItemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DeviceCommStateList)
    }

    static {
      defaultInstance = new DeviceCommStateList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DeviceCommStateList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_DeviceCommStateList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Proto_DeviceCommStateList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_DeviceCommStateList_DeviceCommStateItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Proto_DeviceCommStateList_DeviceCommStateItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031_DeviceCommStateRsp.proto\022\005Proto\"\340\001\n\023D" +
      "eviceCommStateList\022>\n\006dcItem\030\001 \003(\0132..Pro" +
      "to.DeviceCommStateList.DeviceCommStateIt" +
      "em\032\210\001\n\023DeviceCommStateItem\022\n\n\002id\030\001 \002(\003\022\r" +
      "\n\005devid\030\002 \001(\003\022\r\n\005attid\030\003 \001(\014\022\017\n\007attcode\030" +
      "\004 \001(\014\022\016\n\006fvalue\030\005 \002(\002\022\021\n\tcommstate\030\006 \002(\014" +
      "\022\023\n\013commcontent\030\007 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Proto_DeviceCommStateList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proto_DeviceCommStateList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Proto_DeviceCommStateList_descriptor,
        new java.lang.String[] { "DcItem", });
    internal_static_Proto_DeviceCommStateList_DeviceCommStateItem_descriptor =
      internal_static_Proto_DeviceCommStateList_descriptor.getNestedTypes().get(0);
    internal_static_Proto_DeviceCommStateList_DeviceCommStateItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Proto_DeviceCommStateList_DeviceCommStateItem_descriptor,
        new java.lang.String[] { "Id", "Devid", "Attid", "Attcode", "Fvalue", "Commstate", "Commcontent", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
