// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _DeviceDatasRsp.proto

package mina2.jp_tcp.proto;

public final class DeviceDatasRsp {
  private DeviceDatasRsp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NameValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NameValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required bytes name = 1;</code>
     */
    com.google.protobuf.ByteString getName();

    /**
     * <code>required bytes value = 2;</code>
     */
    boolean hasValue();
    /**
     * <code>required bytes value = 2;</code>
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <code>optional bytes unit = 3;</code>
     */
    boolean hasUnit();
    /**
     * <code>optional bytes unit = 3;</code>
     */
    com.google.protobuf.ByteString getUnit();

    /**
     * <code>required int32 state = 4;</code>
     */
    boolean hasState();
    /**
     * <code>required int32 state = 4;</code>
     */
    int getState();
  }
  /**
   * Protobuf type {@code NameValue}
   */
  public static final class NameValue extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NameValue)
      NameValueOrBuilder {
    // Use NameValue.newBuilder() to construct.
    private NameValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NameValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NameValue defaultInstance;
    public static NameValue getDefaultInstance() {
      return defaultInstance;
    }

    public NameValue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NameValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              unit_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              state_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DeviceDatasRsp.internal_static_Proto_NameValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DeviceDatasRsp.internal_static_Proto_NameValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DeviceDatasRsp.NameValue.class, DeviceDatasRsp.NameValue.Builder.class);
    }

    public static com.google.protobuf.Parser<NameValue> PARSER =
        new com.google.protobuf.AbstractParser<NameValue>() {
      public NameValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NameValue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NameValue> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString name_;
    /**
     * <code>required bytes name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes name = 1;</code>
     */
    public com.google.protobuf.ByteString getName() {
      return name_;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>required bytes value = 2;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes value = 2;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int UNIT_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString unit_;
    /**
     * <code>optional bytes unit = 3;</code>
     */
    public boolean hasUnit() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes unit = 3;</code>
     */
    public com.google.protobuf.ByteString getUnit() {
      return unit_;
    }

    public static final int STATE_FIELD_NUMBER = 4;
    private int state_;
    /**
     * <code>required int32 state = 4;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 state = 4;</code>
     */
    public int getState() {
      return state_;
    }

    private void initFields() {
      name_ = com.google.protobuf.ByteString.EMPTY;
      value_ = com.google.protobuf.ByteString.EMPTY;
      unit_ = com.google.protobuf.ByteString.EMPTY;
      state_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, value_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, unit_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, state_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, name_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, value_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, unit_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, state_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DeviceDatasRsp.NameValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceDatasRsp.NameValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceDatasRsp.NameValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceDatasRsp.NameValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceDatasRsp.NameValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeviceDatasRsp.NameValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DeviceDatasRsp.NameValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DeviceDatasRsp.NameValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DeviceDatasRsp.NameValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeviceDatasRsp.NameValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DeviceDatasRsp.NameValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NameValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NameValue)
        DeviceDatasRsp.NameValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DeviceDatasRsp.internal_static_Proto_NameValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DeviceDatasRsp.internal_static_Proto_NameValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DeviceDatasRsp.NameValue.class, DeviceDatasRsp.NameValue.Builder.class);
      }

      // Construct using DeviceDatasRsp.NameValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        unit_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DeviceDatasRsp.internal_static_Proto_NameValue_descriptor;
      }

      public DeviceDatasRsp.NameValue getDefaultInstanceForType() {
        return DeviceDatasRsp.NameValue.getDefaultInstance();
      }

      public DeviceDatasRsp.NameValue build() {
        DeviceDatasRsp.NameValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DeviceDatasRsp.NameValue buildPartial() {
        DeviceDatasRsp.NameValue result = new DeviceDatasRsp.NameValue(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.unit_ = unit_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.state_ = state_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DeviceDatasRsp.NameValue) {
          return mergeFrom((DeviceDatasRsp.NameValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DeviceDatasRsp.NameValue other) {
        if (other == DeviceDatasRsp.NameValue.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasUnit()) {
          setUnit(other.getUnit());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        if (!hasState()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DeviceDatasRsp.NameValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DeviceDatasRsp.NameValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString name_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes name = 1;</code>
       */
      public com.google.protobuf.ByteString getName() {
        return name_;
      }
      /**
       * <code>required bytes name = 1;</code>
       */
      public Builder setName(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes value = 2;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes value = 2;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString unit_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes unit = 3;</code>
       */
      public boolean hasUnit() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes unit = 3;</code>
       */
      public com.google.protobuf.ByteString getUnit() {
        return unit_;
      }
      /**
       * <code>optional bytes unit = 3;</code>
       */
      public Builder setUnit(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        unit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes unit = 3;</code>
       */
      public Builder clearUnit() {
        bitField0_ = (bitField0_ & ~0x00000004);
        unit_ = getDefaultInstance().getUnit();
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <code>required int32 state = 4;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 state = 4;</code>
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>required int32 state = 4;</code>
       */
      public Builder setState(int value) {
        bitField0_ |= 0x00000008;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 state = 4;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000008);
        state_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NameValue)
    }

    static {
      defaultInstance = new NameValue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NameValue)
  }

  public interface DeviceDatasOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeviceDatas)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 deviceId = 1;</code>
     */
    boolean hasDeviceId();
    /**
     * <code>required int64 deviceId = 1;</code>
     */
    long getDeviceId();

    /**
     * <code>repeated .NameValue nv = 2;</code>
     */
    java.util.List<DeviceDatasRsp.NameValue> 
        getNvList();
    /**
     * <code>repeated .NameValue nv = 2;</code>
     */
    DeviceDatasRsp.NameValue getNv(int index);
    /**
     * <code>repeated .NameValue nv = 2;</code>
     */
    int getNvCount();
    /**
     * <code>repeated .NameValue nv = 2;</code>
     */
    java.util.List<? extends DeviceDatasRsp.NameValueOrBuilder> 
        getNvOrBuilderList();
    /**
     * <code>repeated .NameValue nv = 2;</code>
     */
    DeviceDatasRsp.NameValueOrBuilder getNvOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DeviceDatas}
   */
  public static final class DeviceDatas extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DeviceDatas)
      DeviceDatasOrBuilder {
    // Use DeviceDatas.newBuilder() to construct.
    private DeviceDatas(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeviceDatas(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeviceDatas defaultInstance;
    public static DeviceDatas getDefaultInstance() {
      return defaultInstance;
    }

    public DeviceDatas getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceDatas(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              deviceId_ = input.readInt64();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                nv_ = new java.util.ArrayList<DeviceDatasRsp.NameValue>();
                mutable_bitField0_ |= 0x00000002;
              }
              nv_.add(input.readMessage(DeviceDatasRsp.NameValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          nv_ = java.util.Collections.unmodifiableList(nv_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DeviceDatasRsp.internal_static_Proto_DeviceDatas_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DeviceDatasRsp.internal_static_Proto_DeviceDatas_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DeviceDatasRsp.DeviceDatas.class, DeviceDatasRsp.DeviceDatas.Builder.class);
    }

    public static com.google.protobuf.Parser<DeviceDatas> PARSER =
        new com.google.protobuf.AbstractParser<DeviceDatas>() {
      public DeviceDatas parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceDatas(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceDatas> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DEVICEID_FIELD_NUMBER = 1;
    private long deviceId_;
    /**
     * <code>required int64 deviceId = 1;</code>
     */
    public boolean hasDeviceId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 deviceId = 1;</code>
     */
    public long getDeviceId() {
      return deviceId_;
    }

    public static final int NV_FIELD_NUMBER = 2;
    private java.util.List<DeviceDatasRsp.NameValue> nv_;
    /**
     * <code>repeated .NameValue nv = 2;</code>
     */
    public java.util.List<DeviceDatasRsp.NameValue> getNvList() {
      return nv_;
    }
    /**
     * <code>repeated .NameValue nv = 2;</code>
     */
    public java.util.List<? extends DeviceDatasRsp.NameValueOrBuilder> 
        getNvOrBuilderList() {
      return nv_;
    }
    /**
     * <code>repeated .NameValue nv = 2;</code>
     */
    public int getNvCount() {
      return nv_.size();
    }
    /**
     * <code>repeated .NameValue nv = 2;</code>
     */
    public DeviceDatasRsp.NameValue getNv(int index) {
      return nv_.get(index);
    }
    /**
     * <code>repeated .NameValue nv = 2;</code>
     */
    public DeviceDatasRsp.NameValueOrBuilder getNvOrBuilder(
        int index) {
      return nv_.get(index);
    }

    private void initFields() {
      deviceId_ = 0L;
      nv_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDeviceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getNvCount(); i++) {
        if (!getNv(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, deviceId_);
      }
      for (int i = 0; i < nv_.size(); i++) {
        output.writeMessage(2, nv_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, deviceId_);
      }
      for (int i = 0; i < nv_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, nv_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DeviceDatasRsp.DeviceDatas parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceDatasRsp.DeviceDatas parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceDatasRsp.DeviceDatas parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceDatasRsp.DeviceDatas parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceDatasRsp.DeviceDatas parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeviceDatasRsp.DeviceDatas parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DeviceDatasRsp.DeviceDatas parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DeviceDatasRsp.DeviceDatas parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DeviceDatasRsp.DeviceDatas parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeviceDatasRsp.DeviceDatas parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DeviceDatasRsp.DeviceDatas prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DeviceDatas}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeviceDatas)
        DeviceDatasRsp.DeviceDatasOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DeviceDatasRsp.internal_static_Proto_DeviceDatas_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DeviceDatasRsp.internal_static_Proto_DeviceDatas_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DeviceDatasRsp.DeviceDatas.class, DeviceDatasRsp.DeviceDatas.Builder.class);
      }

      // Construct using DeviceDatasRsp.DeviceDatas.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getNvFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        deviceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (nvBuilder_ == null) {
          nv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          nvBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DeviceDatasRsp.internal_static_Proto_DeviceDatas_descriptor;
      }

      public DeviceDatasRsp.DeviceDatas getDefaultInstanceForType() {
        return DeviceDatasRsp.DeviceDatas.getDefaultInstance();
      }

      public DeviceDatasRsp.DeviceDatas build() {
        DeviceDatasRsp.DeviceDatas result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DeviceDatasRsp.DeviceDatas buildPartial() {
        DeviceDatasRsp.DeviceDatas result = new DeviceDatasRsp.DeviceDatas(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.deviceId_ = deviceId_;
        if (nvBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            nv_ = java.util.Collections.unmodifiableList(nv_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.nv_ = nv_;
        } else {
          result.nv_ = nvBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DeviceDatasRsp.DeviceDatas) {
          return mergeFrom((DeviceDatasRsp.DeviceDatas)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DeviceDatasRsp.DeviceDatas other) {
        if (other == DeviceDatasRsp.DeviceDatas.getDefaultInstance()) return this;
        if (other.hasDeviceId()) {
          setDeviceId(other.getDeviceId());
        }
        if (nvBuilder_ == null) {
          if (!other.nv_.isEmpty()) {
            if (nv_.isEmpty()) {
              nv_ = other.nv_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureNvIsMutable();
              nv_.addAll(other.nv_);
            }
            onChanged();
          }
        } else {
          if (!other.nv_.isEmpty()) {
            if (nvBuilder_.isEmpty()) {
              nvBuilder_.dispose();
              nvBuilder_ = null;
              nv_ = other.nv_;
              bitField0_ = (bitField0_ & ~0x00000002);
              nvBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getNvFieldBuilder() : null;
            } else {
              nvBuilder_.addAllMessages(other.nv_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDeviceId()) {
          
          return false;
        }
        for (int i = 0; i < getNvCount(); i++) {
          if (!getNv(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DeviceDatasRsp.DeviceDatas parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DeviceDatasRsp.DeviceDatas) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long deviceId_ ;
      /**
       * <code>required int64 deviceId = 1;</code>
       */
      public boolean hasDeviceId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 deviceId = 1;</code>
       */
      public long getDeviceId() {
        return deviceId_;
      }
      /**
       * <code>required int64 deviceId = 1;</code>
       */
      public Builder setDeviceId(long value) {
        bitField0_ |= 0x00000001;
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 deviceId = 1;</code>
       */
      public Builder clearDeviceId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        deviceId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<DeviceDatasRsp.NameValue> nv_ =
        java.util.Collections.emptyList();
      private void ensureNvIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          nv_ = new java.util.ArrayList<DeviceDatasRsp.NameValue>(nv_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          DeviceDatasRsp.NameValue, DeviceDatasRsp.NameValue.Builder, DeviceDatasRsp.NameValueOrBuilder> nvBuilder_;

      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public java.util.List<DeviceDatasRsp.NameValue> getNvList() {
        if (nvBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nv_);
        } else {
          return nvBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public int getNvCount() {
        if (nvBuilder_ == null) {
          return nv_.size();
        } else {
          return nvBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public DeviceDatasRsp.NameValue getNv(int index) {
        if (nvBuilder_ == null) {
          return nv_.get(index);
        } else {
          return nvBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public Builder setNv(
          int index, DeviceDatasRsp.NameValue value) {
        if (nvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNvIsMutable();
          nv_.set(index, value);
          onChanged();
        } else {
          nvBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public Builder setNv(
          int index, DeviceDatasRsp.NameValue.Builder builderForValue) {
        if (nvBuilder_ == null) {
          ensureNvIsMutable();
          nv_.set(index, builderForValue.build());
          onChanged();
        } else {
          nvBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public Builder addNv(DeviceDatasRsp.NameValue value) {
        if (nvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNvIsMutable();
          nv_.add(value);
          onChanged();
        } else {
          nvBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public Builder addNv(
          int index, DeviceDatasRsp.NameValue value) {
        if (nvBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNvIsMutable();
          nv_.add(index, value);
          onChanged();
        } else {
          nvBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public Builder addNv(
          DeviceDatasRsp.NameValue.Builder builderForValue) {
        if (nvBuilder_ == null) {
          ensureNvIsMutable();
          nv_.add(builderForValue.build());
          onChanged();
        } else {
          nvBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public Builder addNv(
          int index, DeviceDatasRsp.NameValue.Builder builderForValue) {
        if (nvBuilder_ == null) {
          ensureNvIsMutable();
          nv_.add(index, builderForValue.build());
          onChanged();
        } else {
          nvBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public Builder addAllNv(
          java.lang.Iterable<? extends DeviceDatasRsp.NameValue> values) {
        if (nvBuilder_ == null) {
          ensureNvIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nv_);
          onChanged();
        } else {
          nvBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public Builder clearNv() {
        if (nvBuilder_ == null) {
          nv_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          nvBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public Builder removeNv(int index) {
        if (nvBuilder_ == null) {
          ensureNvIsMutable();
          nv_.remove(index);
          onChanged();
        } else {
          nvBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public DeviceDatasRsp.NameValue.Builder getNvBuilder(
          int index) {
        return getNvFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public DeviceDatasRsp.NameValueOrBuilder getNvOrBuilder(
          int index) {
        if (nvBuilder_ == null) {
          return nv_.get(index);  } else {
          return nvBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public java.util.List<? extends DeviceDatasRsp.NameValueOrBuilder> 
           getNvOrBuilderList() {
        if (nvBuilder_ != null) {
          return nvBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nv_);
        }
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public DeviceDatasRsp.NameValue.Builder addNvBuilder() {
        return getNvFieldBuilder().addBuilder(
            DeviceDatasRsp.NameValue.getDefaultInstance());
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public DeviceDatasRsp.NameValue.Builder addNvBuilder(
          int index) {
        return getNvFieldBuilder().addBuilder(
            index, DeviceDatasRsp.NameValue.getDefaultInstance());
      }
      /**
       * <code>repeated .NameValue nv = 2;</code>
       */
      public java.util.List<DeviceDatasRsp.NameValue.Builder> 
           getNvBuilderList() {
        return getNvFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          DeviceDatasRsp.NameValue, DeviceDatasRsp.NameValue.Builder, DeviceDatasRsp.NameValueOrBuilder> 
          getNvFieldBuilder() {
        if (nvBuilder_ == null) {
          nvBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              DeviceDatasRsp.NameValue, DeviceDatasRsp.NameValue.Builder, DeviceDatasRsp.NameValueOrBuilder>(
                  nv_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          nv_ = null;
        }
        return nvBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DeviceDatas)
    }

    static {
      defaultInstance = new DeviceDatas(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DeviceDatas)
  }

  public interface DeviceDataListRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeviceDataListRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .DeviceDatas dataItem = 1;</code>
     */
    java.util.List<DeviceDatasRsp.DeviceDatas> 
        getDataItemList();
    /**
     * <code>repeated .DeviceDatas dataItem = 1;</code>
     */
    DeviceDatasRsp.DeviceDatas getDataItem(int index);
    /**
     * <code>repeated .DeviceDatas dataItem = 1;</code>
     */
    int getDataItemCount();
    /**
     * <code>repeated .DeviceDatas dataItem = 1;</code>
     */
    java.util.List<? extends DeviceDatasRsp.DeviceDatasOrBuilder> 
        getDataItemOrBuilderList();
    /**
     * <code>repeated .DeviceDatas dataItem = 1;</code>
     */
    DeviceDatasRsp.DeviceDatasOrBuilder getDataItemOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DeviceDataListRsp}
   */
  public static final class DeviceDataListRsp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DeviceDataListRsp)
      DeviceDataListRspOrBuilder {
    // Use DeviceDataListRsp.newBuilder() to construct.
    private DeviceDataListRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeviceDataListRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeviceDataListRsp defaultInstance;
    public static DeviceDataListRsp getDefaultInstance() {
      return defaultInstance;
    }

    public DeviceDataListRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceDataListRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                dataItem_ = new java.util.ArrayList<DeviceDatasRsp.DeviceDatas>();
                mutable_bitField0_ |= 0x00000001;
              }
              dataItem_.add(input.readMessage(DeviceDatasRsp.DeviceDatas.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          dataItem_ = java.util.Collections.unmodifiableList(dataItem_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return DeviceDatasRsp.internal_static_Proto_DeviceDataListRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return DeviceDatasRsp.internal_static_Proto_DeviceDataListRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              DeviceDatasRsp.DeviceDataListRsp.class, DeviceDatasRsp.DeviceDataListRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<DeviceDataListRsp> PARSER =
        new com.google.protobuf.AbstractParser<DeviceDataListRsp>() {
      public DeviceDataListRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceDataListRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceDataListRsp> getParserForType() {
      return PARSER;
    }

    public static final int DATAITEM_FIELD_NUMBER = 1;
    private java.util.List<DeviceDatasRsp.DeviceDatas> dataItem_;
    /**
     * <code>repeated .DeviceDatas dataItem = 1;</code>
     */
    public java.util.List<DeviceDatasRsp.DeviceDatas> getDataItemList() {
      return dataItem_;
    }
    /**
     * <code>repeated .DeviceDatas dataItem = 1;</code>
     */
    public java.util.List<? extends DeviceDatasRsp.DeviceDatasOrBuilder> 
        getDataItemOrBuilderList() {
      return dataItem_;
    }
    /**
     * <code>repeated .DeviceDatas dataItem = 1;</code>
     */
    public int getDataItemCount() {
      return dataItem_.size();
    }
    /**
     * <code>repeated .DeviceDatas dataItem = 1;</code>
     */
    public DeviceDatasRsp.DeviceDatas getDataItem(int index) {
      return dataItem_.get(index);
    }
    /**
     * <code>repeated .DeviceDatas dataItem = 1;</code>
     */
    public DeviceDatasRsp.DeviceDatasOrBuilder getDataItemOrBuilder(
        int index) {
      return dataItem_.get(index);
    }

    private void initFields() {
      dataItem_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getDataItemCount(); i++) {
        if (!getDataItem(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < dataItem_.size(); i++) {
        output.writeMessage(1, dataItem_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < dataItem_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, dataItem_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static DeviceDatasRsp.DeviceDataListRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceDatasRsp.DeviceDataListRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceDatasRsp.DeviceDataListRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static DeviceDatasRsp.DeviceDataListRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static DeviceDatasRsp.DeviceDataListRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeviceDatasRsp.DeviceDataListRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static DeviceDatasRsp.DeviceDataListRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static DeviceDatasRsp.DeviceDataListRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static DeviceDatasRsp.DeviceDataListRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static DeviceDatasRsp.DeviceDataListRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(DeviceDatasRsp.DeviceDataListRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DeviceDataListRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeviceDataListRsp)
        DeviceDatasRsp.DeviceDataListRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return DeviceDatasRsp.internal_static_Proto_DeviceDataListRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return DeviceDatasRsp.internal_static_Proto_DeviceDataListRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                DeviceDatasRsp.DeviceDataListRsp.class, DeviceDatasRsp.DeviceDataListRsp.Builder.class);
      }

      // Construct using DeviceDatasRsp.DeviceDataListRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataItemFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (dataItemBuilder_ == null) {
          dataItem_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataItemBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return DeviceDatasRsp.internal_static_Proto_DeviceDataListRsp_descriptor;
      }

      public DeviceDatasRsp.DeviceDataListRsp getDefaultInstanceForType() {
        return DeviceDatasRsp.DeviceDataListRsp.getDefaultInstance();
      }

      public DeviceDatasRsp.DeviceDataListRsp build() {
        DeviceDatasRsp.DeviceDataListRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public DeviceDatasRsp.DeviceDataListRsp buildPartial() {
        DeviceDatasRsp.DeviceDataListRsp result = new DeviceDatasRsp.DeviceDataListRsp(this);
        int from_bitField0_ = bitField0_;
        if (dataItemBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            dataItem_ = java.util.Collections.unmodifiableList(dataItem_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dataItem_ = dataItem_;
        } else {
          result.dataItem_ = dataItemBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof DeviceDatasRsp.DeviceDataListRsp) {
          return mergeFrom((DeviceDatasRsp.DeviceDataListRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(DeviceDatasRsp.DeviceDataListRsp other) {
        if (other == DeviceDatasRsp.DeviceDataListRsp.getDefaultInstance()) return this;
        if (dataItemBuilder_ == null) {
          if (!other.dataItem_.isEmpty()) {
            if (dataItem_.isEmpty()) {
              dataItem_ = other.dataItem_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataItemIsMutable();
              dataItem_.addAll(other.dataItem_);
            }
            onChanged();
          }
        } else {
          if (!other.dataItem_.isEmpty()) {
            if (dataItemBuilder_.isEmpty()) {
              dataItemBuilder_.dispose();
              dataItemBuilder_ = null;
              dataItem_ = other.dataItem_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataItemBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataItemFieldBuilder() : null;
            } else {
              dataItemBuilder_.addAllMessages(other.dataItem_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getDataItemCount(); i++) {
          if (!getDataItem(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        DeviceDatasRsp.DeviceDataListRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (DeviceDatasRsp.DeviceDataListRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<DeviceDatasRsp.DeviceDatas> dataItem_ =
        java.util.Collections.emptyList();
      private void ensureDataItemIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          dataItem_ = new java.util.ArrayList<DeviceDatasRsp.DeviceDatas>(dataItem_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          DeviceDatasRsp.DeviceDatas, DeviceDatasRsp.DeviceDatas.Builder, DeviceDatasRsp.DeviceDatasOrBuilder> dataItemBuilder_;

      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public java.util.List<DeviceDatasRsp.DeviceDatas> getDataItemList() {
        if (dataItemBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dataItem_);
        } else {
          return dataItemBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public int getDataItemCount() {
        if (dataItemBuilder_ == null) {
          return dataItem_.size();
        } else {
          return dataItemBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public DeviceDatasRsp.DeviceDatas getDataItem(int index) {
        if (dataItemBuilder_ == null) {
          return dataItem_.get(index);
        } else {
          return dataItemBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public Builder setDataItem(
          int index, DeviceDatasRsp.DeviceDatas value) {
        if (dataItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataItemIsMutable();
          dataItem_.set(index, value);
          onChanged();
        } else {
          dataItemBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public Builder setDataItem(
          int index, DeviceDatasRsp.DeviceDatas.Builder builderForValue) {
        if (dataItemBuilder_ == null) {
          ensureDataItemIsMutable();
          dataItem_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataItemBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public Builder addDataItem(DeviceDatasRsp.DeviceDatas value) {
        if (dataItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataItemIsMutable();
          dataItem_.add(value);
          onChanged();
        } else {
          dataItemBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public Builder addDataItem(
          int index, DeviceDatasRsp.DeviceDatas value) {
        if (dataItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataItemIsMutable();
          dataItem_.add(index, value);
          onChanged();
        } else {
          dataItemBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public Builder addDataItem(
          DeviceDatasRsp.DeviceDatas.Builder builderForValue) {
        if (dataItemBuilder_ == null) {
          ensureDataItemIsMutable();
          dataItem_.add(builderForValue.build());
          onChanged();
        } else {
          dataItemBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public Builder addDataItem(
          int index, DeviceDatasRsp.DeviceDatas.Builder builderForValue) {
        if (dataItemBuilder_ == null) {
          ensureDataItemIsMutable();
          dataItem_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataItemBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public Builder addAllDataItem(
          java.lang.Iterable<? extends DeviceDatasRsp.DeviceDatas> values) {
        if (dataItemBuilder_ == null) {
          ensureDataItemIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dataItem_);
          onChanged();
        } else {
          dataItemBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public Builder clearDataItem() {
        if (dataItemBuilder_ == null) {
          dataItem_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataItemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public Builder removeDataItem(int index) {
        if (dataItemBuilder_ == null) {
          ensureDataItemIsMutable();
          dataItem_.remove(index);
          onChanged();
        } else {
          dataItemBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public DeviceDatasRsp.DeviceDatas.Builder getDataItemBuilder(
          int index) {
        return getDataItemFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public DeviceDatasRsp.DeviceDatasOrBuilder getDataItemOrBuilder(
          int index) {
        if (dataItemBuilder_ == null) {
          return dataItem_.get(index);  } else {
          return dataItemBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public java.util.List<? extends DeviceDatasRsp.DeviceDatasOrBuilder> 
           getDataItemOrBuilderList() {
        if (dataItemBuilder_ != null) {
          return dataItemBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dataItem_);
        }
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public DeviceDatasRsp.DeviceDatas.Builder addDataItemBuilder() {
        return getDataItemFieldBuilder().addBuilder(
            DeviceDatasRsp.DeviceDatas.getDefaultInstance());
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public DeviceDatasRsp.DeviceDatas.Builder addDataItemBuilder(
          int index) {
        return getDataItemFieldBuilder().addBuilder(
            index, DeviceDatasRsp.DeviceDatas.getDefaultInstance());
      }
      /**
       * <code>repeated .DeviceDatas dataItem = 1;</code>
       */
      public java.util.List<DeviceDatasRsp.DeviceDatas.Builder> 
           getDataItemBuilderList() {
        return getDataItemFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          DeviceDatasRsp.DeviceDatas, DeviceDatasRsp.DeviceDatas.Builder, DeviceDatasRsp.DeviceDatasOrBuilder> 
          getDataItemFieldBuilder() {
        if (dataItemBuilder_ == null) {
          dataItemBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              DeviceDatasRsp.DeviceDatas, DeviceDatasRsp.DeviceDatas.Builder, DeviceDatasRsp.DeviceDatasOrBuilder>(
                  dataItem_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          dataItem_ = null;
        }
        return dataItemBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:DeviceDataListRsp)
    }

    static {
      defaultInstance = new DeviceDataListRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DeviceDataListRsp)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_NameValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Proto_NameValue_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_DeviceDatas_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Proto_DeviceDatas_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_DeviceDataListRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Proto_DeviceDataListRsp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025_DeviceDatasRsp.proto\022\005Proto\"E\n\tNameVa" +
      "lue\022\014\n\004name\030\001 \002(\014\022\r\n\005value\030\002 \002(\014\022\014\n\004unit" +
      "\030\003 \001(\014\022\r\n\005state\030\004 \002(\005\"=\n\013DeviceDatas\022\020\n\010" +
      "deviceId\030\001 \002(\003\022\034\n\002nv\030\002 \003(\0132\020.NameV" +
      "alue\"9\n\021DeviceDataListRsp\022$\n\010dataItem\030\001 " +
      "\003(\0132\022.DeviceDatas"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Proto_NameValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proto_NameValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Proto_NameValue_descriptor,
        new java.lang.String[] { "Name", "Value", "Unit", "State", });
    internal_static_Proto_DeviceDatas_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Proto_DeviceDatas_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Proto_DeviceDatas_descriptor,
        new java.lang.String[] { "DeviceId", "Nv", });
    internal_static_Proto_DeviceDataListRsp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Proto_DeviceDataListRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Proto_DeviceDataListRsp_descriptor,
        new java.lang.String[] { "DataItem", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
