// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _GetDevAttcodeListItemReq.proto

package mina2.jp_tcp.proto;

public final class GetDevAttcodeListItemReq {
  private GetDevAttcodeListItemReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReadDeviceCountListReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReadDeviceCountListReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes devid = 1;</code>
     */
    boolean hasDevid();
    /**
     * <code>required bytes devid = 1;</code>
     */
    com.google.protobuf.ByteString getDevid();

    /**
     * <code>required bytes devtype = 2;</code>
     */
    boolean hasDevtype();
    /**
     * <code>required bytes devtype = 2;</code>
     */
    com.google.protobuf.ByteString getDevtype();

    /**
     * <code>required bytes mestype = 3;</code>
     */
    boolean hasMestype();
    /**
     * <code>required bytes mestype = 3;</code>
     */
    com.google.protobuf.ByteString getMestype();

    /**
     * <code>required bytes dlgtype = 4;</code>
     */
    boolean hasDlgtype();
    /**
     * <code>required bytes dlgtype = 4;</code>
     */
    com.google.protobuf.ByteString getDlgtype();

    /**
     * <code>optional bytes params = 5;</code>
     */
    boolean hasParams();
    /**
     * <code>optional bytes params = 5;</code>
     */
    com.google.protobuf.ByteString getParams();
  }
  /**
   * Protobuf type {@code ReadDeviceCountListReq}
   */
  public static final class ReadDeviceCountListReq extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReadDeviceCountListReq)
      ReadDeviceCountListReqOrBuilder {
    // Use ReadDeviceCountListReq.newBuilder() to construct.
    private ReadDeviceCountListReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReadDeviceCountListReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReadDeviceCountListReq defaultInstance;
    public static ReadDeviceCountListReq getDefaultInstance() {
      return defaultInstance;
    }

    public ReadDeviceCountListReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReadDeviceCountListReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              devid_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              devtype_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              mestype_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              dlgtype_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              params_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GetDevAttcodeListItemReq.internal_static_Proto_ReadDeviceCountListReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GetDevAttcodeListItemReq.internal_static_Proto_ReadDeviceCountListReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetDevAttcodeListItemReq.ReadDeviceCountListReq.class, GetDevAttcodeListItemReq.ReadDeviceCountListReq.Builder.class);
    }

    public static com.google.protobuf.Parser<ReadDeviceCountListReq> PARSER =
        new com.google.protobuf.AbstractParser<ReadDeviceCountListReq>() {
      public ReadDeviceCountListReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReadDeviceCountListReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReadDeviceCountListReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DEVID_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString devid_;
    /**
     * <code>required bytes devid = 1;</code>
     */
    public boolean hasDevid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes devid = 1;</code>
     */
    public com.google.protobuf.ByteString getDevid() {
      return devid_;
    }

    public static final int DEVTYPE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString devtype_;
    /**
     * <code>required bytes devtype = 2;</code>
     */
    public boolean hasDevtype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes devtype = 2;</code>
     */
    public com.google.protobuf.ByteString getDevtype() {
      return devtype_;
    }

    public static final int MESTYPE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString mestype_;
    /**
     * <code>required bytes mestype = 3;</code>
     */
    public boolean hasMestype() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes mestype = 3;</code>
     */
    public com.google.protobuf.ByteString getMestype() {
      return mestype_;
    }

    public static final int DLGTYPE_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString dlgtype_;
    /**
     * <code>required bytes dlgtype = 4;</code>
     */
    public boolean hasDlgtype() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes dlgtype = 4;</code>
     */
    public com.google.protobuf.ByteString getDlgtype() {
      return dlgtype_;
    }

    public static final int PARAMS_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString params_;
    /**
     * <code>optional bytes params = 5;</code>
     */
    public boolean hasParams() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes params = 5;</code>
     */
    public com.google.protobuf.ByteString getParams() {
      return params_;
    }

    private void initFields() {
      devid_ = com.google.protobuf.ByteString.EMPTY;
      devtype_ = com.google.protobuf.ByteString.EMPTY;
      mestype_ = com.google.protobuf.ByteString.EMPTY;
      dlgtype_ = com.google.protobuf.ByteString.EMPTY;
      params_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasDevid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDevtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMestype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDlgtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, devid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, devtype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, mestype_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, dlgtype_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, params_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, devid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, devtype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, mestype_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, dlgtype_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, params_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static GetDevAttcodeListItemReq.ReadDeviceCountListReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetDevAttcodeListItemReq.ReadDeviceCountListReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetDevAttcodeListItemReq.ReadDeviceCountListReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static GetDevAttcodeListItemReq.ReadDeviceCountListReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static GetDevAttcodeListItemReq.ReadDeviceCountListReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GetDevAttcodeListItemReq.ReadDeviceCountListReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static GetDevAttcodeListItemReq.ReadDeviceCountListReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static GetDevAttcodeListItemReq.ReadDeviceCountListReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static GetDevAttcodeListItemReq.ReadDeviceCountListReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static GetDevAttcodeListItemReq.ReadDeviceCountListReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(GetDevAttcodeListItemReq.ReadDeviceCountListReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReadDeviceCountListReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReadDeviceCountListReq)
        GetDevAttcodeListItemReq.ReadDeviceCountListReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GetDevAttcodeListItemReq.internal_static_Proto_ReadDeviceCountListReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GetDevAttcodeListItemReq.internal_static_Proto_ReadDeviceCountListReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                GetDevAttcodeListItemReq.ReadDeviceCountListReq.class, GetDevAttcodeListItemReq.ReadDeviceCountListReq.Builder.class);
      }

      // Construct using GetDevAttcodeListItemReq.ReadDeviceCountListReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        devid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        devtype_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        mestype_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        dlgtype_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        params_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GetDevAttcodeListItemReq.internal_static_Proto_ReadDeviceCountListReq_descriptor;
      }

      public GetDevAttcodeListItemReq.ReadDeviceCountListReq getDefaultInstanceForType() {
        return GetDevAttcodeListItemReq.ReadDeviceCountListReq.getDefaultInstance();
      }

      public GetDevAttcodeListItemReq.ReadDeviceCountListReq build() {
        GetDevAttcodeListItemReq.ReadDeviceCountListReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public GetDevAttcodeListItemReq.ReadDeviceCountListReq buildPartial() {
        GetDevAttcodeListItemReq.ReadDeviceCountListReq result = new GetDevAttcodeListItemReq.ReadDeviceCountListReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.devid_ = devid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.devtype_ = devtype_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.mestype_ = mestype_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.dlgtype_ = dlgtype_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.params_ = params_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof GetDevAttcodeListItemReq.ReadDeviceCountListReq) {
          return mergeFrom((GetDevAttcodeListItemReq.ReadDeviceCountListReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(GetDevAttcodeListItemReq.ReadDeviceCountListReq other) {
        if (other == GetDevAttcodeListItemReq.ReadDeviceCountListReq.getDefaultInstance()) return this;
        if (other.hasDevid()) {
          setDevid(other.getDevid());
        }
        if (other.hasDevtype()) {
          setDevtype(other.getDevtype());
        }
        if (other.hasMestype()) {
          setMestype(other.getMestype());
        }
        if (other.hasDlgtype()) {
          setDlgtype(other.getDlgtype());
        }
        if (other.hasParams()) {
          setParams(other.getParams());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasDevid()) {
          
          return false;
        }
        if (!hasDevtype()) {
          
          return false;
        }
        if (!hasMestype()) {
          
          return false;
        }
        if (!hasDlgtype()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        GetDevAttcodeListItemReq.ReadDeviceCountListReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (GetDevAttcodeListItemReq.ReadDeviceCountListReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString devid_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes devid = 1;</code>
       */
      public boolean hasDevid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes devid = 1;</code>
       */
      public com.google.protobuf.ByteString getDevid() {
        return devid_;
      }
      /**
       * <code>required bytes devid = 1;</code>
       */
      public Builder setDevid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        devid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes devid = 1;</code>
       */
      public Builder clearDevid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        devid_ = getDefaultInstance().getDevid();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString devtype_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes devtype = 2;</code>
       */
      public boolean hasDevtype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes devtype = 2;</code>
       */
      public com.google.protobuf.ByteString getDevtype() {
        return devtype_;
      }
      /**
       * <code>required bytes devtype = 2;</code>
       */
      public Builder setDevtype(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        devtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes devtype = 2;</code>
       */
      public Builder clearDevtype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        devtype_ = getDefaultInstance().getDevtype();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString mestype_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes mestype = 3;</code>
       */
      public boolean hasMestype() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes mestype = 3;</code>
       */
      public com.google.protobuf.ByteString getMestype() {
        return mestype_;
      }
      /**
       * <code>required bytes mestype = 3;</code>
       */
      public Builder setMestype(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        mestype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes mestype = 3;</code>
       */
      public Builder clearMestype() {
        bitField0_ = (bitField0_ & ~0x00000004);
        mestype_ = getDefaultInstance().getMestype();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dlgtype_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes dlgtype = 4;</code>
       */
      public boolean hasDlgtype() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required bytes dlgtype = 4;</code>
       */
      public com.google.protobuf.ByteString getDlgtype() {
        return dlgtype_;
      }
      /**
       * <code>required bytes dlgtype = 4;</code>
       */
      public Builder setDlgtype(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        dlgtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes dlgtype = 4;</code>
       */
      public Builder clearDlgtype() {
        bitField0_ = (bitField0_ & ~0x00000008);
        dlgtype_ = getDefaultInstance().getDlgtype();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString params_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes params = 5;</code>
       */
      public boolean hasParams() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bytes params = 5;</code>
       */
      public com.google.protobuf.ByteString getParams() {
        return params_;
      }
      /**
       * <code>optional bytes params = 5;</code>
       */
      public Builder setParams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        params_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes params = 5;</code>
       */
      public Builder clearParams() {
        bitField0_ = (bitField0_ & ~0x00000010);
        params_ = getDefaultInstance().getParams();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReadDeviceCountListReq)
    }

    static {
      defaultInstance = new ReadDeviceCountListReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReadDeviceCountListReq)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_ReadDeviceCountListReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Proto_ReadDeviceCountListReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037_GetDevAttcodeListItemReq.proto\022\005Proto" +
      "\"j\n\026ReadDeviceCountListReq\022\r\n\005devid\030\001 \002(" +
      "\014\022\017\n\007devtype\030\002 \002(\014\022\017\n\007mestype\030\003 \002(\014\022\017\n\007d" +
      "lgtype\030\004 \002(\014\022\016\n\006params\030\005 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Proto_ReadDeviceCountListReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proto_ReadDeviceCountListReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Proto_ReadDeviceCountListReq_descriptor,
        new java.lang.String[] { "Devid", "Devtype", "Mestype", "Dlgtype", "Params", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
