// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _PowerConsumptionRsp.proto

package mina2.jp_tcp.proto;

public final class PowerConsumptionRspOuterClass {
  private PowerConsumptionRspOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PowerConsumptionRspOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PowerConsumptionRsp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
     */
    java.util.List<PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem> 
        getPowerConsumptionListList();
    /**
     * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
     */
    PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem getPowerConsumptionList(int index);
    /**
     * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
     */
    int getPowerConsumptionListCount();
    /**
     * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
     */
    java.util.List<? extends PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItemOrBuilder> 
        getPowerConsumptionListOrBuilderList();
    /**
     * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
     */
    PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItemOrBuilder getPowerConsumptionListOrBuilder(
        int index);

    /**
     * <code>required bytes mestype = 2;</code>
     */
    boolean hasMestype();
    /**
     * <code>required bytes mestype = 2;</code>
     */
    com.google.protobuf.ByteString getMestype();

    /**
     * <code>required bytes dlgtype = 3;</code>
     */
    boolean hasDlgtype();
    /**
     * <code>required bytes dlgtype = 3;</code>
     */
    com.google.protobuf.ByteString getDlgtype();

    /**
     * <code>optional bytes params = 4;</code>
     */
    boolean hasParams();
    /**
     * <code>optional bytes params = 4;</code>
     */
    com.google.protobuf.ByteString getParams();
  }
  /**
   * Protobuf type {@code PowerConsumptionRsp}
   */
  public static final class PowerConsumptionRsp extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:PowerConsumptionRsp)
      PowerConsumptionRspOrBuilder {
    // Use PowerConsumptionRsp.newBuilder() to construct.
    private PowerConsumptionRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PowerConsumptionRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PowerConsumptionRsp defaultInstance;
    public static PowerConsumptionRsp getDefaultInstance() {
      return defaultInstance;
    }

    public PowerConsumptionRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PowerConsumptionRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                powerConsumptionList_ = new java.util.ArrayList<PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              powerConsumptionList_.add(input.readMessage(PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              mestype_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              dlgtype_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              params_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          powerConsumptionList_ = java.util.Collections.unmodifiableList(powerConsumptionList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PowerConsumptionRspOuterClass.internal_static_Proto_PowerConsumptionRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PowerConsumptionRspOuterClass.internal_static_Proto_PowerConsumptionRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PowerConsumptionRspOuterClass.PowerConsumptionRsp.class, PowerConsumptionRspOuterClass.PowerConsumptionRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<PowerConsumptionRsp> PARSER =
        new com.google.protobuf.AbstractParser<PowerConsumptionRsp>() {
      public PowerConsumptionRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PowerConsumptionRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PowerConsumptionRsp> getParserForType() {
      return PARSER;
    }

    public interface PowerConsumptionItemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:PowerConsumptionRsp.PowerConsumptionItem)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required bytes devicetype = 1;</code>
       */
      boolean hasDevicetype();
      /**
       * <code>required bytes devicetype = 1;</code>
       */
      com.google.protobuf.ByteString getDevicetype();

      /**
       * <code>required float devicepc = 2;</code>
       */
      boolean hasDevicepc();
      /**
       * <code>required float devicepc = 2;</code>
       */
      float getDevicepc();

      /**
       * <code>optional bytes devunit = 3;</code>
       */
      boolean hasDevunit();
      /**
       * <code>optional bytes devunit = 3;</code>
       */
      com.google.protobuf.ByteString getDevunit();
    }
    /**
     * Protobuf type {@code PowerConsumptionRsp.PowerConsumptionItem}
     */
    public static final class PowerConsumptionItem extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:PowerConsumptionRsp.PowerConsumptionItem)
        PowerConsumptionItemOrBuilder {
      // Use PowerConsumptionItem.newBuilder() to construct.
      private PowerConsumptionItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private PowerConsumptionItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final PowerConsumptionItem defaultInstance;
      public static PowerConsumptionItem getDefaultInstance() {
        return defaultInstance;
      }

      public PowerConsumptionItem getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private PowerConsumptionItem(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                devicetype_ = input.readBytes();
                break;
              }
              case 21: {
                bitField0_ |= 0x00000002;
                devicepc_ = input.readFloat();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                devunit_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PowerConsumptionRspOuterClass.internal_static_Proto_PowerConsumptionRsp_PowerConsumptionItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PowerConsumptionRspOuterClass.internal_static_Proto_PowerConsumptionRsp_PowerConsumptionItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.class, PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.Builder.class);
      }

      public static com.google.protobuf.Parser<PowerConsumptionItem> PARSER =
          new com.google.protobuf.AbstractParser<PowerConsumptionItem>() {
        public PowerConsumptionItem parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new PowerConsumptionItem(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<PowerConsumptionItem> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int DEVICETYPE_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString devicetype_;
      /**
       * <code>required bytes devicetype = 1;</code>
       */
      public boolean hasDevicetype() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes devicetype = 1;</code>
       */
      public com.google.protobuf.ByteString getDevicetype() {
        return devicetype_;
      }

      public static final int DEVICEPC_FIELD_NUMBER = 2;
      private float devicepc_;
      /**
       * <code>required float devicepc = 2;</code>
       */
      public boolean hasDevicepc() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float devicepc = 2;</code>
       */
      public float getDevicepc() {
        return devicepc_;
      }

      public static final int DEVUNIT_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString devunit_;
      /**
       * <code>optional bytes devunit = 3;</code>
       */
      public boolean hasDevunit() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes devunit = 3;</code>
       */
      public com.google.protobuf.ByteString getDevunit() {
        return devunit_;
      }

      private void initFields() {
        devicetype_ = com.google.protobuf.ByteString.EMPTY;
        devicepc_ = 0F;
        devunit_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasDevicetype()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDevicepc()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, devicetype_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeFloat(2, devicepc_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, devunit_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, devicetype_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(2, devicepc_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, devunit_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code PowerConsumptionRsp.PowerConsumptionItem}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:PowerConsumptionRsp.PowerConsumptionItem)
          PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return PowerConsumptionRspOuterClass.internal_static_Proto_PowerConsumptionRsp_PowerConsumptionItem_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return PowerConsumptionRspOuterClass.internal_static_Proto_PowerConsumptionRsp_PowerConsumptionItem_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.class, PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.Builder.class);
        }

        // Construct using PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          devicetype_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          devicepc_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000002);
          devunit_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return PowerConsumptionRspOuterClass.internal_static_Proto_PowerConsumptionRsp_PowerConsumptionItem_descriptor;
        }

        public PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem getDefaultInstanceForType() {
          return PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.getDefaultInstance();
        }

        public PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem build() {
          PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem buildPartial() {
          PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem result = new PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.devicetype_ = devicetype_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.devicepc_ = devicepc_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.devunit_ = devunit_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem) {
            return mergeFrom((PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem other) {
          if (other == PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.getDefaultInstance()) return this;
          if (other.hasDevicetype()) {
            setDevicetype(other.getDevicetype());
          }
          if (other.hasDevicepc()) {
            setDevicepc(other.getDevicepc());
          }
          if (other.hasDevunit()) {
            setDevunit(other.getDevunit());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasDevicetype()) {
            
            return false;
          }
          if (!hasDevicepc()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.ByteString devicetype_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes devicetype = 1;</code>
         */
        public boolean hasDevicetype() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required bytes devicetype = 1;</code>
         */
        public com.google.protobuf.ByteString getDevicetype() {
          return devicetype_;
        }
        /**
         * <code>required bytes devicetype = 1;</code>
         */
        public Builder setDevicetype(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          devicetype_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes devicetype = 1;</code>
         */
        public Builder clearDevicetype() {
          bitField0_ = (bitField0_ & ~0x00000001);
          devicetype_ = getDefaultInstance().getDevicetype();
          onChanged();
          return this;
        }

        private float devicepc_ ;
        /**
         * <code>required float devicepc = 2;</code>
         */
        public boolean hasDevicepc() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required float devicepc = 2;</code>
         */
        public float getDevicepc() {
          return devicepc_;
        }
        /**
         * <code>required float devicepc = 2;</code>
         */
        public Builder setDevicepc(float value) {
          bitField0_ |= 0x00000002;
          devicepc_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required float devicepc = 2;</code>
         */
        public Builder clearDevicepc() {
          bitField0_ = (bitField0_ & ~0x00000002);
          devicepc_ = 0F;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString devunit_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes devunit = 3;</code>
         */
        public boolean hasDevunit() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional bytes devunit = 3;</code>
         */
        public com.google.protobuf.ByteString getDevunit() {
          return devunit_;
        }
        /**
         * <code>optional bytes devunit = 3;</code>
         */
        public Builder setDevunit(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          devunit_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes devunit = 3;</code>
         */
        public Builder clearDevunit() {
          bitField0_ = (bitField0_ & ~0x00000004);
          devunit_ = getDefaultInstance().getDevunit();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:PowerConsumptionRsp.PowerConsumptionItem)
      }

      static {
        defaultInstance = new PowerConsumptionItem(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:PowerConsumptionRsp.PowerConsumptionItem)
    }

    private int bitField0_;
    public static final int POWERCONSUMPTIONLIST_FIELD_NUMBER = 1;
    private java.util.List<PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem> powerConsumptionList_;
    /**
     * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
     */
    public java.util.List<PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem> getPowerConsumptionListList() {
      return powerConsumptionList_;
    }
    /**
     * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
     */
    public java.util.List<? extends PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItemOrBuilder> 
        getPowerConsumptionListOrBuilderList() {
      return powerConsumptionList_;
    }
    /**
     * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
     */
    public int getPowerConsumptionListCount() {
      return powerConsumptionList_.size();
    }
    /**
     * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
     */
    public PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem getPowerConsumptionList(int index) {
      return powerConsumptionList_.get(index);
    }
    /**
     * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
     */
    public PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItemOrBuilder getPowerConsumptionListOrBuilder(
        int index) {
      return powerConsumptionList_.get(index);
    }

    public static final int MESTYPE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString mestype_;
    /**
     * <code>required bytes mestype = 2;</code>
     */
    public boolean hasMestype() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes mestype = 2;</code>
     */
    public com.google.protobuf.ByteString getMestype() {
      return mestype_;
    }

    public static final int DLGTYPE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString dlgtype_;
    /**
     * <code>required bytes dlgtype = 3;</code>
     */
    public boolean hasDlgtype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes dlgtype = 3;</code>
     */
    public com.google.protobuf.ByteString getDlgtype() {
      return dlgtype_;
    }

    public static final int PARAMS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString params_;
    /**
     * <code>optional bytes params = 4;</code>
     */
    public boolean hasParams() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes params = 4;</code>
     */
    public com.google.protobuf.ByteString getParams() {
      return params_;
    }

    private void initFields() {
      powerConsumptionList_ = java.util.Collections.emptyList();
      mestype_ = com.google.protobuf.ByteString.EMPTY;
      dlgtype_ = com.google.protobuf.ByteString.EMPTY;
      params_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMestype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDlgtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPowerConsumptionListCount(); i++) {
        if (!getPowerConsumptionList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < powerConsumptionList_.size(); i++) {
        output.writeMessage(1, powerConsumptionList_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, mestype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, dlgtype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, params_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < powerConsumptionList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, powerConsumptionList_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, mestype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, dlgtype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, params_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static PowerConsumptionRspOuterClass.PowerConsumptionRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PowerConsumptionRspOuterClass.PowerConsumptionRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PowerConsumptionRspOuterClass.PowerConsumptionRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PowerConsumptionRspOuterClass.PowerConsumptionRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PowerConsumptionRspOuterClass.PowerConsumptionRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PowerConsumptionRspOuterClass.PowerConsumptionRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static PowerConsumptionRspOuterClass.PowerConsumptionRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static PowerConsumptionRspOuterClass.PowerConsumptionRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static PowerConsumptionRspOuterClass.PowerConsumptionRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static PowerConsumptionRspOuterClass.PowerConsumptionRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(PowerConsumptionRspOuterClass.PowerConsumptionRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PowerConsumptionRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PowerConsumptionRsp)
        PowerConsumptionRspOuterClass.PowerConsumptionRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PowerConsumptionRspOuterClass.internal_static_Proto_PowerConsumptionRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PowerConsumptionRspOuterClass.internal_static_Proto_PowerConsumptionRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PowerConsumptionRspOuterClass.PowerConsumptionRsp.class, PowerConsumptionRspOuterClass.PowerConsumptionRsp.Builder.class);
      }

      // Construct using PowerConsumptionRspOuterClass.PowerConsumptionRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPowerConsumptionListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (powerConsumptionListBuilder_ == null) {
          powerConsumptionList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          powerConsumptionListBuilder_.clear();
        }
        mestype_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        dlgtype_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        params_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PowerConsumptionRspOuterClass.internal_static_Proto_PowerConsumptionRsp_descriptor;
      }

      public PowerConsumptionRspOuterClass.PowerConsumptionRsp getDefaultInstanceForType() {
        return PowerConsumptionRspOuterClass.PowerConsumptionRsp.getDefaultInstance();
      }

      public PowerConsumptionRspOuterClass.PowerConsumptionRsp build() {
        PowerConsumptionRspOuterClass.PowerConsumptionRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public PowerConsumptionRspOuterClass.PowerConsumptionRsp buildPartial() {
        PowerConsumptionRspOuterClass.PowerConsumptionRsp result = new PowerConsumptionRspOuterClass.PowerConsumptionRsp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (powerConsumptionListBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            powerConsumptionList_ = java.util.Collections.unmodifiableList(powerConsumptionList_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.powerConsumptionList_ = powerConsumptionList_;
        } else {
          result.powerConsumptionList_ = powerConsumptionListBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mestype_ = mestype_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dlgtype_ = dlgtype_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.params_ = params_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PowerConsumptionRspOuterClass.PowerConsumptionRsp) {
          return mergeFrom((PowerConsumptionRspOuterClass.PowerConsumptionRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PowerConsumptionRspOuterClass.PowerConsumptionRsp other) {
        if (other == PowerConsumptionRspOuterClass.PowerConsumptionRsp.getDefaultInstance()) return this;
        if (powerConsumptionListBuilder_ == null) {
          if (!other.powerConsumptionList_.isEmpty()) {
            if (powerConsumptionList_.isEmpty()) {
              powerConsumptionList_ = other.powerConsumptionList_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePowerConsumptionListIsMutable();
              powerConsumptionList_.addAll(other.powerConsumptionList_);
            }
            onChanged();
          }
        } else {
          if (!other.powerConsumptionList_.isEmpty()) {
            if (powerConsumptionListBuilder_.isEmpty()) {
              powerConsumptionListBuilder_.dispose();
              powerConsumptionListBuilder_ = null;
              powerConsumptionList_ = other.powerConsumptionList_;
              bitField0_ = (bitField0_ & ~0x00000001);
              powerConsumptionListBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPowerConsumptionListFieldBuilder() : null;
            } else {
              powerConsumptionListBuilder_.addAllMessages(other.powerConsumptionList_);
            }
          }
        }
        if (other.hasMestype()) {
          setMestype(other.getMestype());
        }
        if (other.hasDlgtype()) {
          setDlgtype(other.getDlgtype());
        }
        if (other.hasParams()) {
          setParams(other.getParams());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMestype()) {
          
          return false;
        }
        if (!hasDlgtype()) {
          
          return false;
        }
        for (int i = 0; i < getPowerConsumptionListCount(); i++) {
          if (!getPowerConsumptionList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PowerConsumptionRspOuterClass.PowerConsumptionRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PowerConsumptionRspOuterClass.PowerConsumptionRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem> powerConsumptionList_ =
        java.util.Collections.emptyList();
      private void ensurePowerConsumptionListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          powerConsumptionList_ = new java.util.ArrayList<PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem>(powerConsumptionList_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem, PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.Builder, PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItemOrBuilder> powerConsumptionListBuilder_;

      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public java.util.List<PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem> getPowerConsumptionListList() {
        if (powerConsumptionListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(powerConsumptionList_);
        } else {
          return powerConsumptionListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public int getPowerConsumptionListCount() {
        if (powerConsumptionListBuilder_ == null) {
          return powerConsumptionList_.size();
        } else {
          return powerConsumptionListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem getPowerConsumptionList(int index) {
        if (powerConsumptionListBuilder_ == null) {
          return powerConsumptionList_.get(index);
        } else {
          return powerConsumptionListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public Builder setPowerConsumptionList(
          int index, PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem value) {
        if (powerConsumptionListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePowerConsumptionListIsMutable();
          powerConsumptionList_.set(index, value);
          onChanged();
        } else {
          powerConsumptionListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public Builder setPowerConsumptionList(
          int index, PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.Builder builderForValue) {
        if (powerConsumptionListBuilder_ == null) {
          ensurePowerConsumptionListIsMutable();
          powerConsumptionList_.set(index, builderForValue.build());
          onChanged();
        } else {
          powerConsumptionListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public Builder addPowerConsumptionList(PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem value) {
        if (powerConsumptionListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePowerConsumptionListIsMutable();
          powerConsumptionList_.add(value);
          onChanged();
        } else {
          powerConsumptionListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public Builder addPowerConsumptionList(
          int index, PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem value) {
        if (powerConsumptionListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePowerConsumptionListIsMutable();
          powerConsumptionList_.add(index, value);
          onChanged();
        } else {
          powerConsumptionListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public Builder addPowerConsumptionList(
          PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.Builder builderForValue) {
        if (powerConsumptionListBuilder_ == null) {
          ensurePowerConsumptionListIsMutable();
          powerConsumptionList_.add(builderForValue.build());
          onChanged();
        } else {
          powerConsumptionListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public Builder addPowerConsumptionList(
          int index, PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.Builder builderForValue) {
        if (powerConsumptionListBuilder_ == null) {
          ensurePowerConsumptionListIsMutable();
          powerConsumptionList_.add(index, builderForValue.build());
          onChanged();
        } else {
          powerConsumptionListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public Builder addAllPowerConsumptionList(
          java.lang.Iterable<? extends PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem> values) {
        if (powerConsumptionListBuilder_ == null) {
          ensurePowerConsumptionListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, powerConsumptionList_);
          onChanged();
        } else {
          powerConsumptionListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public Builder clearPowerConsumptionList() {
        if (powerConsumptionListBuilder_ == null) {
          powerConsumptionList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          powerConsumptionListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public Builder removePowerConsumptionList(int index) {
        if (powerConsumptionListBuilder_ == null) {
          ensurePowerConsumptionListIsMutable();
          powerConsumptionList_.remove(index);
          onChanged();
        } else {
          powerConsumptionListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.Builder getPowerConsumptionListBuilder(
          int index) {
        return getPowerConsumptionListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItemOrBuilder getPowerConsumptionListOrBuilder(
          int index) {
        if (powerConsumptionListBuilder_ == null) {
          return powerConsumptionList_.get(index);  } else {
          return powerConsumptionListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public java.util.List<? extends PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItemOrBuilder> 
           getPowerConsumptionListOrBuilderList() {
        if (powerConsumptionListBuilder_ != null) {
          return powerConsumptionListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(powerConsumptionList_);
        }
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.Builder addPowerConsumptionListBuilder() {
        return getPowerConsumptionListFieldBuilder().addBuilder(
            PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.getDefaultInstance());
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.Builder addPowerConsumptionListBuilder(
          int index) {
        return getPowerConsumptionListFieldBuilder().addBuilder(
            index, PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.getDefaultInstance());
      }
      /**
       * <code>repeated .PowerConsumptionRsp.PowerConsumptionItem powerConsumptionList = 1;</code>
       */
      public java.util.List<PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.Builder> 
           getPowerConsumptionListBuilderList() {
        return getPowerConsumptionListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem, PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.Builder, PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItemOrBuilder> 
          getPowerConsumptionListFieldBuilder() {
        if (powerConsumptionListBuilder_ == null) {
          powerConsumptionListBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem, PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItem.Builder, PowerConsumptionRspOuterClass.PowerConsumptionRsp.PowerConsumptionItemOrBuilder>(
                  powerConsumptionList_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          powerConsumptionList_ = null;
        }
        return powerConsumptionListBuilder_;
      }

      private com.google.protobuf.ByteString mestype_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes mestype = 2;</code>
       */
      public boolean hasMestype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes mestype = 2;</code>
       */
      public com.google.protobuf.ByteString getMestype() {
        return mestype_;
      }
      /**
       * <code>required bytes mestype = 2;</code>
       */
      public Builder setMestype(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mestype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes mestype = 2;</code>
       */
      public Builder clearMestype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mestype_ = getDefaultInstance().getMestype();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dlgtype_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes dlgtype = 3;</code>
       */
      public boolean hasDlgtype() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes dlgtype = 3;</code>
       */
      public com.google.protobuf.ByteString getDlgtype() {
        return dlgtype_;
      }
      /**
       * <code>required bytes dlgtype = 3;</code>
       */
      public Builder setDlgtype(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dlgtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes dlgtype = 3;</code>
       */
      public Builder clearDlgtype() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dlgtype_ = getDefaultInstance().getDlgtype();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString params_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes params = 4;</code>
       */
      public boolean hasParams() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes params = 4;</code>
       */
      public com.google.protobuf.ByteString getParams() {
        return params_;
      }
      /**
       * <code>optional bytes params = 4;</code>
       */
      public Builder setParams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        params_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes params = 4;</code>
       */
      public Builder clearParams() {
        bitField0_ = (bitField0_ & ~0x00000008);
        params_ = getDefaultInstance().getParams();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:PowerConsumptionRsp)
    }

    static {
      defaultInstance = new PowerConsumptionRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:PowerConsumptionRsp)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_PowerConsumptionRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Proto_PowerConsumptionRsp_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_PowerConsumptionRsp_PowerConsumptionItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Proto_PowerConsumptionRsp_PowerConsumptionItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032_PowerConsumptionRsp.proto\022\005Proto\"\345\001\n\023" +
      "PowerConsumptionRsp\022M\n\024powerConsumptionL" +
      "ist\030\001 \003(\0132/.PowerConsumptionRsp.Po" +
      "werConsumptionItem\022\017\n\007mestype\030\002 \002(\014\022\017\n\007d" +
      "lgtype\030\003 \002(\014\022\016\n\006params\030\004 \001(\014\032M\n\024PowerCon" +
      "sumptionItem\022\022\n\ndevicetype\030\001 \002(\014\022\020\n\010devi" +
      "cepc\030\002 \002(\002\022\017\n\007devunit\030\003 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Proto_PowerConsumptionRsp_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proto_PowerConsumptionRsp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Proto_PowerConsumptionRsp_descriptor,
        new java.lang.String[] { "PowerConsumptionList", "Mestype", "Dlgtype", "Params", });
    internal_static_Proto_PowerConsumptionRsp_PowerConsumptionItem_descriptor =
      internal_static_Proto_PowerConsumptionRsp_descriptor.getNestedTypes().get(0);
    internal_static_Proto_PowerConsumptionRsp_PowerConsumptionItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Proto_PowerConsumptionRsp_PowerConsumptionItem_descriptor,
        new java.lang.String[] { "Devicetype", "Devicepc", "Devunit", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
