// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _ReadRealdataItemRsp.proto

package mina2.jp_tcp.proto;

public final class ReadRealdataItemRsp {
  private ReadRealdataItemRsp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReadRealDataListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReadRealDataList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
     */
    java.util.List<ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem> 
        getRdiList();
    /**
     * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
     */
    ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem getRdi(int index);
    /**
     * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
     */
    int getRdiCount();
    /**
     * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
     */
    java.util.List<? extends ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItemOrBuilder> 
        getRdiOrBuilderList();
    /**
     * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
     */
    ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItemOrBuilder getRdiOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ReadRealDataList}
   */
  public static final class ReadRealDataList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReadRealDataList)
      ReadRealDataListOrBuilder {
    // Use ReadRealDataList.newBuilder() to construct.
    private ReadRealDataList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReadRealDataList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReadRealDataList defaultInstance;
    public static ReadRealDataList getDefaultInstance() {
      return defaultInstance;
    }

    public ReadRealDataList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReadRealDataList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                rdi_ = new java.util.ArrayList<ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              rdi_.add(input.readMessage(ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          rdi_ = java.util.Collections.unmodifiableList(rdi_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ReadRealdataItemRsp.internal_static_Proto_ReadRealDataList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ReadRealdataItemRsp.internal_static_Proto_ReadRealDataList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReadRealdataItemRsp.ReadRealDataList.class, ReadRealdataItemRsp.ReadRealDataList.Builder.class);
    }

    public static com.google.protobuf.Parser<ReadRealDataList> PARSER =
        new com.google.protobuf.AbstractParser<ReadRealDataList>() {
      public ReadRealDataList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReadRealDataList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReadRealDataList> getParserForType() {
      return PARSER;
    }

    public interface ReadRealDataItemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:ReadRealDataList.ReadRealDataItem)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required bytes id = 1;</code>
       *
       * <pre>
       *�豸���Ա��
       * </pre>
       */
      boolean hasId();
      /**
       * <code>required bytes id = 1;</code>
       *
       * <pre>
       *�豸���Ա��
       * </pre>
       */
      com.google.protobuf.ByteString getId();

      /**
       * <code>required int64 devid = 2;</code>
       *
       * <pre>
       *�豸���
       * </pre>
       */
      boolean hasDevid();
      /**
       * <code>required int64 devid = 2;</code>
       *
       * <pre>
       *�豸���
       * </pre>
       */
      long getDevid();

      /**
       * <code>optional bytes attcode = 3;</code>
       *
       * <pre>
       *�豸���Ա���
       * </pre>
       */
      boolean hasAttcode();
      /**
       * <code>optional bytes attcode = 3;</code>
       *
       * <pre>
       *�豸���Ա���
       * </pre>
       */
      com.google.protobuf.ByteString getAttcode();

      /**
       * <code>required float fvalue = 4;</code>
       */
      boolean hasFvalue();
      /**
       * <code>required float fvalue = 4;</code>
       */
      float getFvalue();

      /**
       * <code>required bytes state = 5;</code>
       */
      boolean hasState();
      /**
       * <code>required bytes state = 5;</code>
       */
      com.google.protobuf.ByteString getState();

      /**
       * <code>optional bytes unit = 6;</code>
       */
      boolean hasUnit();
      /**
       * <code>optional bytes unit = 6;</code>
       */
      com.google.protobuf.ByteString getUnit();

      /**
       * <code>optional bytes thirdDevid = 7;</code>
       *
       * <pre>
       *����ϵͳ �豸���
       * </pre>
       */
      boolean hasThirdDevid();
      /**
       * <code>optional bytes thirdDevid = 7;</code>
       *
       * <pre>
       *����ϵͳ �豸���
       * </pre>
       */
      com.google.protobuf.ByteString getThirdDevid();

      /**
       * <code>optional bytes thirdAttid = 8;</code>
       *
       * <pre>
       *����ϵͳ �豸���Ա��
       * </pre>
       */
      boolean hasThirdAttid();
      /**
       * <code>optional bytes thirdAttid = 8;</code>
       *
       * <pre>
       *����ϵͳ �豸���Ա��
       * </pre>
       */
      com.google.protobuf.ByteString getThirdAttid();
    }
    /**
     * Protobuf type {@code ReadRealDataList.ReadRealDataItem}
     */
    public static final class ReadRealDataItem extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:ReadRealDataList.ReadRealDataItem)
        ReadRealDataItemOrBuilder {
      // Use ReadRealDataItem.newBuilder() to construct.
      private ReadRealDataItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private ReadRealDataItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final ReadRealDataItem defaultInstance;
      public static ReadRealDataItem getDefaultInstance() {
        return defaultInstance;
      }

      public ReadRealDataItem getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private ReadRealDataItem(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                id_ = input.readBytes();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                devid_ = input.readInt64();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                attcode_ = input.readBytes();
                break;
              }
              case 37: {
                bitField0_ |= 0x00000008;
                fvalue_ = input.readFloat();
                break;
              }
              case 42: {
                bitField0_ |= 0x00000010;
                state_ = input.readBytes();
                break;
              }
              case 50: {
                bitField0_ |= 0x00000020;
                unit_ = input.readBytes();
                break;
              }
              case 58: {
                bitField0_ |= 0x00000040;
                thirdDevid_ = input.readBytes();
                break;
              }
              case 66: {
                bitField0_ |= 0x00000080;
                thirdAttid_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReadRealdataItemRsp.internal_static_Proto_ReadRealDataList_ReadRealDataItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReadRealdataItemRsp.internal_static_Proto_ReadRealDataList_ReadRealDataItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.class, ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.Builder.class);
      }

      public static com.google.protobuf.Parser<ReadRealDataItem> PARSER =
          new com.google.protobuf.AbstractParser<ReadRealDataItem>() {
        public ReadRealDataItem parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ReadRealDataItem(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<ReadRealDataItem> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int ID_FIELD_NUMBER = 1;
      private com.google.protobuf.ByteString id_;
      /**
       * <code>required bytes id = 1;</code>
       *
       * <pre>
       *�豸���Ա��
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes id = 1;</code>
       *
       * <pre>
       *�豸���Ա��
       * </pre>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }

      public static final int DEVID_FIELD_NUMBER = 2;
      private long devid_;
      /**
       * <code>required int64 devid = 2;</code>
       *
       * <pre>
       *�豸���
       * </pre>
       */
      public boolean hasDevid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 devid = 2;</code>
       *
       * <pre>
       *�豸���
       * </pre>
       */
      public long getDevid() {
        return devid_;
      }

      public static final int ATTCODE_FIELD_NUMBER = 3;
      private com.google.protobuf.ByteString attcode_;
      /**
       * <code>optional bytes attcode = 3;</code>
       *
       * <pre>
       *�豸���Ա���
       * </pre>
       */
      public boolean hasAttcode() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes attcode = 3;</code>
       *
       * <pre>
       *�豸���Ա���
       * </pre>
       */
      public com.google.protobuf.ByteString getAttcode() {
        return attcode_;
      }

      public static final int FVALUE_FIELD_NUMBER = 4;
      private float fvalue_;
      /**
       * <code>required float fvalue = 4;</code>
       */
      public boolean hasFvalue() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required float fvalue = 4;</code>
       */
      public float getFvalue() {
        return fvalue_;
      }

      public static final int STATE_FIELD_NUMBER = 5;
      private com.google.protobuf.ByteString state_;
      /**
       * <code>required bytes state = 5;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bytes state = 5;</code>
       */
      public com.google.protobuf.ByteString getState() {
        return state_;
      }

      public static final int UNIT_FIELD_NUMBER = 6;
      private com.google.protobuf.ByteString unit_;
      /**
       * <code>optional bytes unit = 6;</code>
       */
      public boolean hasUnit() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes unit = 6;</code>
       */
      public com.google.protobuf.ByteString getUnit() {
        return unit_;
      }

      public static final int THIRDDEVID_FIELD_NUMBER = 7;
      private com.google.protobuf.ByteString thirdDevid_;
      /**
       * <code>optional bytes thirdDevid = 7;</code>
       *
       * <pre>
       *����ϵͳ �豸���
       * </pre>
       */
      public boolean hasThirdDevid() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes thirdDevid = 7;</code>
       *
       * <pre>
       *����ϵͳ �豸���
       * </pre>
       */
      public com.google.protobuf.ByteString getThirdDevid() {
        return thirdDevid_;
      }

      public static final int THIRDATTID_FIELD_NUMBER = 8;
      private com.google.protobuf.ByteString thirdAttid_;
      /**
       * <code>optional bytes thirdAttid = 8;</code>
       *
       * <pre>
       *����ϵͳ �豸���Ա��
       * </pre>
       */
      public boolean hasThirdAttid() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes thirdAttid = 8;</code>
       *
       * <pre>
       *����ϵͳ �豸���Ա��
       * </pre>
       */
      public com.google.protobuf.ByteString getThirdAttid() {
        return thirdAttid_;
      }

      private void initFields() {
        id_ = com.google.protobuf.ByteString.EMPTY;
        devid_ = 0L;
        attcode_ = com.google.protobuf.ByteString.EMPTY;
        fvalue_ = 0F;
        state_ = com.google.protobuf.ByteString.EMPTY;
        unit_ = com.google.protobuf.ByteString.EMPTY;
        thirdDevid_ = com.google.protobuf.ByteString.EMPTY;
        thirdAttid_ = com.google.protobuf.ByteString.EMPTY;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasId()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasDevid()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasFvalue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasState()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, devid_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, attcode_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeFloat(4, fvalue_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeBytes(5, state_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeBytes(6, unit_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeBytes(7, thirdDevid_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          output.writeBytes(8, thirdAttid_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, devid_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, attcode_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(4, fvalue_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(5, state_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(6, unit_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(7, thirdDevid_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(8, thirdAttid_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code ReadRealDataList.ReadRealDataItem}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:ReadRealDataList.ReadRealDataItem)
          ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItemOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return ReadRealdataItemRsp.internal_static_Proto_ReadRealDataList_ReadRealDataItem_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return ReadRealdataItemRsp.internal_static_Proto_ReadRealDataList_ReadRealDataItem_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.class, ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.Builder.class);
        }

        // Construct using ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000001);
          devid_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          attcode_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000004);
          fvalue_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000008);
          state_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000010);
          unit_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000020);
          thirdDevid_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000040);
          thirdAttid_ = com.google.protobuf.ByteString.EMPTY;
          bitField0_ = (bitField0_ & ~0x00000080);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return ReadRealdataItemRsp.internal_static_Proto_ReadRealDataList_ReadRealDataItem_descriptor;
        }

        public ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem getDefaultInstanceForType() {
          return ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.getDefaultInstance();
        }

        public ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem build() {
          ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem buildPartial() {
          ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem result = new ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.devid_ = devid_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.attcode_ = attcode_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.fvalue_ = fvalue_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.state_ = state_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.unit_ = unit_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.thirdDevid_ = thirdDevid_;
          if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
            to_bitField0_ |= 0x00000080;
          }
          result.thirdAttid_ = thirdAttid_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem) {
            return mergeFrom((ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem other) {
          if (other == ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasDevid()) {
            setDevid(other.getDevid());
          }
          if (other.hasAttcode()) {
            setAttcode(other.getAttcode());
          }
          if (other.hasFvalue()) {
            setFvalue(other.getFvalue());
          }
          if (other.hasState()) {
            setState(other.getState());
          }
          if (other.hasUnit()) {
            setUnit(other.getUnit());
          }
          if (other.hasThirdDevid()) {
            setThirdDevid(other.getThirdDevid());
          }
          if (other.hasThirdAttid()) {
            setThirdAttid(other.getThirdAttid());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasId()) {
            
            return false;
          }
          if (!hasDevid()) {
            
            return false;
          }
          if (!hasFvalue()) {
            
            return false;
          }
          if (!hasState()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes id = 1;</code>
         *
         * <pre>
         *�豸���Ա��
         * </pre>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required bytes id = 1;</code>
         *
         * <pre>
         *�豸���Ա��
         * </pre>
         */
        public com.google.protobuf.ByteString getId() {
          return id_;
        }
        /**
         * <code>required bytes id = 1;</code>
         *
         * <pre>
         *�豸���Ա��
         * </pre>
         */
        public Builder setId(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes id = 1;</code>
         *
         * <pre>
         *�豸���Ա��
         * </pre>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = getDefaultInstance().getId();
          onChanged();
          return this;
        }

        private long devid_ ;
        /**
         * <code>required int64 devid = 2;</code>
         *
         * <pre>
         *�豸���
         * </pre>
         */
        public boolean hasDevid() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required int64 devid = 2;</code>
         *
         * <pre>
         *�豸���
         * </pre>
         */
        public long getDevid() {
          return devid_;
        }
        /**
         * <code>required int64 devid = 2;</code>
         *
         * <pre>
         *�豸���
         * </pre>
         */
        public Builder setDevid(long value) {
          bitField0_ |= 0x00000002;
          devid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required int64 devid = 2;</code>
         *
         * <pre>
         *�豸���
         * </pre>
         */
        public Builder clearDevid() {
          bitField0_ = (bitField0_ & ~0x00000002);
          devid_ = 0L;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString attcode_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes attcode = 3;</code>
         *
         * <pre>
         *�豸���Ա���
         * </pre>
         */
        public boolean hasAttcode() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional bytes attcode = 3;</code>
         *
         * <pre>
         *�豸���Ա���
         * </pre>
         */
        public com.google.protobuf.ByteString getAttcode() {
          return attcode_;
        }
        /**
         * <code>optional bytes attcode = 3;</code>
         *
         * <pre>
         *�豸���Ա���
         * </pre>
         */
        public Builder setAttcode(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          attcode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes attcode = 3;</code>
         *
         * <pre>
         *�豸���Ա���
         * </pre>
         */
        public Builder clearAttcode() {
          bitField0_ = (bitField0_ & ~0x00000004);
          attcode_ = getDefaultInstance().getAttcode();
          onChanged();
          return this;
        }

        private float fvalue_ ;
        /**
         * <code>required float fvalue = 4;</code>
         */
        public boolean hasFvalue() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>required float fvalue = 4;</code>
         */
        public float getFvalue() {
          return fvalue_;
        }
        /**
         * <code>required float fvalue = 4;</code>
         */
        public Builder setFvalue(float value) {
          bitField0_ |= 0x00000008;
          fvalue_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required float fvalue = 4;</code>
         */
        public Builder clearFvalue() {
          bitField0_ = (bitField0_ & ~0x00000008);
          fvalue_ = 0F;
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString state_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>required bytes state = 5;</code>
         */
        public boolean hasState() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>required bytes state = 5;</code>
         */
        public com.google.protobuf.ByteString getState() {
          return state_;
        }
        /**
         * <code>required bytes state = 5;</code>
         */
        public Builder setState(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
          state_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required bytes state = 5;</code>
         */
        public Builder clearState() {
          bitField0_ = (bitField0_ & ~0x00000010);
          state_ = getDefaultInstance().getState();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString unit_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes unit = 6;</code>
         */
        public boolean hasUnit() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional bytes unit = 6;</code>
         */
        public com.google.protobuf.ByteString getUnit() {
          return unit_;
        }
        /**
         * <code>optional bytes unit = 6;</code>
         */
        public Builder setUnit(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
          unit_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes unit = 6;</code>
         */
        public Builder clearUnit() {
          bitField0_ = (bitField0_ & ~0x00000020);
          unit_ = getDefaultInstance().getUnit();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString thirdDevid_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes thirdDevid = 7;</code>
         *
         * <pre>
         *����ϵͳ �豸���
         * </pre>
         */
        public boolean hasThirdDevid() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional bytes thirdDevid = 7;</code>
         *
         * <pre>
         *����ϵͳ �豸���
         * </pre>
         */
        public com.google.protobuf.ByteString getThirdDevid() {
          return thirdDevid_;
        }
        /**
         * <code>optional bytes thirdDevid = 7;</code>
         *
         * <pre>
         *����ϵͳ �豸���
         * </pre>
         */
        public Builder setThirdDevid(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          thirdDevid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes thirdDevid = 7;</code>
         *
         * <pre>
         *����ϵͳ �豸���
         * </pre>
         */
        public Builder clearThirdDevid() {
          bitField0_ = (bitField0_ & ~0x00000040);
          thirdDevid_ = getDefaultInstance().getThirdDevid();
          onChanged();
          return this;
        }

        private com.google.protobuf.ByteString thirdAttid_ = com.google.protobuf.ByteString.EMPTY;
        /**
         * <code>optional bytes thirdAttid = 8;</code>
         *
         * <pre>
         *����ϵͳ �豸���Ա��
         * </pre>
         */
        public boolean hasThirdAttid() {
          return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        /**
         * <code>optional bytes thirdAttid = 8;</code>
         *
         * <pre>
         *����ϵͳ �豸���Ա��
         * </pre>
         */
        public com.google.protobuf.ByteString getThirdAttid() {
          return thirdAttid_;
        }
        /**
         * <code>optional bytes thirdAttid = 8;</code>
         *
         * <pre>
         *����ϵͳ �豸���Ա��
         * </pre>
         */
        public Builder setThirdAttid(com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
          thirdAttid_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional bytes thirdAttid = 8;</code>
         *
         * <pre>
         *����ϵͳ �豸���Ա��
         * </pre>
         */
        public Builder clearThirdAttid() {
          bitField0_ = (bitField0_ & ~0x00000080);
          thirdAttid_ = getDefaultInstance().getThirdAttid();
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:ReadRealDataList.ReadRealDataItem)
      }

      static {
        defaultInstance = new ReadRealDataItem(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:ReadRealDataList.ReadRealDataItem)
    }

    public static final int RDI_FIELD_NUMBER = 1;
    private java.util.List<ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem> rdi_;
    /**
     * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
     */
    public java.util.List<ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem> getRdiList() {
      return rdi_;
    }
    /**
     * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
     */
    public java.util.List<? extends ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItemOrBuilder> 
        getRdiOrBuilderList() {
      return rdi_;
    }
    /**
     * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
     */
    public int getRdiCount() {
      return rdi_.size();
    }
    /**
     * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
     */
    public ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem getRdi(int index) {
      return rdi_.get(index);
    }
    /**
     * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
     */
    public ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItemOrBuilder getRdiOrBuilder(
        int index) {
      return rdi_.get(index);
    }

    private void initFields() {
      rdi_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getRdiCount(); i++) {
        if (!getRdi(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < rdi_.size(); i++) {
        output.writeMessage(1, rdi_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < rdi_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, rdi_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ReadRealdataItemRsp.ReadRealDataList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReadRealdataItemRsp.ReadRealDataList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReadRealdataItemRsp.ReadRealDataList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReadRealdataItemRsp.ReadRealDataList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReadRealdataItemRsp.ReadRealDataList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ReadRealdataItemRsp.ReadRealDataList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ReadRealdataItemRsp.ReadRealDataList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ReadRealdataItemRsp.ReadRealDataList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ReadRealdataItemRsp.ReadRealDataList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ReadRealdataItemRsp.ReadRealDataList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ReadRealdataItemRsp.ReadRealDataList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReadRealDataList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReadRealDataList)
        ReadRealdataItemRsp.ReadRealDataListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReadRealdataItemRsp.internal_static_Proto_ReadRealDataList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReadRealdataItemRsp.internal_static_Proto_ReadRealDataList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReadRealdataItemRsp.ReadRealDataList.class, ReadRealdataItemRsp.ReadRealDataList.Builder.class);
      }

      // Construct using ReadRealdataItemRsp.ReadRealDataList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRdiFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (rdiBuilder_ == null) {
          rdi_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          rdiBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ReadRealdataItemRsp.internal_static_Proto_ReadRealDataList_descriptor;
      }

      public ReadRealdataItemRsp.ReadRealDataList getDefaultInstanceForType() {
        return ReadRealdataItemRsp.ReadRealDataList.getDefaultInstance();
      }

      public ReadRealdataItemRsp.ReadRealDataList build() {
        ReadRealdataItemRsp.ReadRealDataList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ReadRealdataItemRsp.ReadRealDataList buildPartial() {
        ReadRealdataItemRsp.ReadRealDataList result = new ReadRealdataItemRsp.ReadRealDataList(this);
        int from_bitField0_ = bitField0_;
        if (rdiBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            rdi_ = java.util.Collections.unmodifiableList(rdi_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.rdi_ = rdi_;
        } else {
          result.rdi_ = rdiBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReadRealdataItemRsp.ReadRealDataList) {
          return mergeFrom((ReadRealdataItemRsp.ReadRealDataList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReadRealdataItemRsp.ReadRealDataList other) {
        if (other == ReadRealdataItemRsp.ReadRealDataList.getDefaultInstance()) return this;
        if (rdiBuilder_ == null) {
          if (!other.rdi_.isEmpty()) {
            if (rdi_.isEmpty()) {
              rdi_ = other.rdi_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRdiIsMutable();
              rdi_.addAll(other.rdi_);
            }
            onChanged();
          }
        } else {
          if (!other.rdi_.isEmpty()) {
            if (rdiBuilder_.isEmpty()) {
              rdiBuilder_.dispose();
              rdiBuilder_ = null;
              rdi_ = other.rdi_;
              bitField0_ = (bitField0_ & ~0x00000001);
              rdiBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRdiFieldBuilder() : null;
            } else {
              rdiBuilder_.addAllMessages(other.rdi_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getRdiCount(); i++) {
          if (!getRdi(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReadRealdataItemRsp.ReadRealDataList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReadRealdataItemRsp.ReadRealDataList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem> rdi_ =
        java.util.Collections.emptyList();
      private void ensureRdiIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          rdi_ = new java.util.ArrayList<ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem>(rdi_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem, ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.Builder, ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItemOrBuilder> rdiBuilder_;

      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public java.util.List<ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem> getRdiList() {
        if (rdiBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rdi_);
        } else {
          return rdiBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public int getRdiCount() {
        if (rdiBuilder_ == null) {
          return rdi_.size();
        } else {
          return rdiBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem getRdi(int index) {
        if (rdiBuilder_ == null) {
          return rdi_.get(index);
        } else {
          return rdiBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public Builder setRdi(
          int index, ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem value) {
        if (rdiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRdiIsMutable();
          rdi_.set(index, value);
          onChanged();
        } else {
          rdiBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public Builder setRdi(
          int index, ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.Builder builderForValue) {
        if (rdiBuilder_ == null) {
          ensureRdiIsMutable();
          rdi_.set(index, builderForValue.build());
          onChanged();
        } else {
          rdiBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public Builder addRdi(ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem value) {
        if (rdiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRdiIsMutable();
          rdi_.add(value);
          onChanged();
        } else {
          rdiBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public Builder addRdi(
          int index, ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem value) {
        if (rdiBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRdiIsMutable();
          rdi_.add(index, value);
          onChanged();
        } else {
          rdiBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public Builder addRdi(
          ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.Builder builderForValue) {
        if (rdiBuilder_ == null) {
          ensureRdiIsMutable();
          rdi_.add(builderForValue.build());
          onChanged();
        } else {
          rdiBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public Builder addRdi(
          int index, ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.Builder builderForValue) {
        if (rdiBuilder_ == null) {
          ensureRdiIsMutable();
          rdi_.add(index, builderForValue.build());
          onChanged();
        } else {
          rdiBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public Builder addAllRdi(
          java.lang.Iterable<? extends ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem> values) {
        if (rdiBuilder_ == null) {
          ensureRdiIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rdi_);
          onChanged();
        } else {
          rdiBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public Builder clearRdi() {
        if (rdiBuilder_ == null) {
          rdi_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          rdiBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public Builder removeRdi(int index) {
        if (rdiBuilder_ == null) {
          ensureRdiIsMutable();
          rdi_.remove(index);
          onChanged();
        } else {
          rdiBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.Builder getRdiBuilder(
          int index) {
        return getRdiFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItemOrBuilder getRdiOrBuilder(
          int index) {
        if (rdiBuilder_ == null) {
          return rdi_.get(index);  } else {
          return rdiBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public java.util.List<? extends ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItemOrBuilder> 
           getRdiOrBuilderList() {
        if (rdiBuilder_ != null) {
          return rdiBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rdi_);
        }
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.Builder addRdiBuilder() {
        return getRdiFieldBuilder().addBuilder(
            ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.getDefaultInstance());
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.Builder addRdiBuilder(
          int index) {
        return getRdiFieldBuilder().addBuilder(
            index, ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.getDefaultInstance());
      }
      /**
       * <code>repeated .ReadRealDataList.ReadRealDataItem rdi = 1;</code>
       */
      public java.util.List<ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.Builder> 
           getRdiBuilderList() {
        return getRdiFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem, ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.Builder, ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItemOrBuilder> 
          getRdiFieldBuilder() {
        if (rdiBuilder_ == null) {
          rdiBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem, ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItem.Builder, ReadRealdataItemRsp.ReadRealDataList.ReadRealDataItemOrBuilder>(
                  rdi_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          rdi_ = null;
        }
        return rdiBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ReadRealDataList)
    }

    static {
      defaultInstance = new ReadRealDataList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReadRealDataList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_ReadRealDataList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Proto_ReadRealDataList_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_ReadRealDataList_ReadRealDataItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Proto_ReadRealDataList_ReadRealDataItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032_ReadRealdataItemRsp.proto\022\005Proto\"\337\001\n\020" +
      "ReadRealDataList\0225\n\003rdi\030\001 \003(\0132(.Re" +
      "adRealDataList.ReadRealDataItem\032\223\001\n\020Read" +
      "RealDataItem\022\n\n\002id\030\001 \002(\014\022\r\n\005devid\030\002 \002(\003\022" +
      "\017\n\007attcode\030\003 \001(\014\022\016\n\006fvalue\030\004 \002(\002\022\r\n\005stat" +
      "e\030\005 \002(\014\022\014\n\004unit\030\006 \001(\014\022\022\n\nthirdDevid\030\007 \001(" +
      "\014\022\022\n\nthirdAttid\030\010 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Proto_ReadRealDataList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proto_ReadRealDataList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Proto_ReadRealDataList_descriptor,
        new java.lang.String[] { "Rdi", });
    internal_static_Proto_ReadRealDataList_ReadRealDataItem_descriptor =
      internal_static_Proto_ReadRealDataList_descriptor.getNestedTypes().get(0);
    internal_static_Proto_ReadRealDataList_ReadRealDataItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Proto_ReadRealDataList_ReadRealDataItem_descriptor,
        new java.lang.String[] { "Id", "Devid", "Attcode", "Fvalue", "State", "Unit", "ThirdDevid", "ThirdAttid", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
