// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: _ReadDeviceCountListReq.proto

package mina2.jp_tcp.proto;

public final class ReadDeviceCountListReq {
  private ReadDeviceCountListReq() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface DeviceItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeviceItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated bytes devicetype = 1;</code>
     */
    java.util.List<com.google.protobuf.ByteString> getDevicetypeList();
    /**
     * <code>repeated bytes devicetype = 1;</code>
     */
    int getDevicetypeCount();
    /**
     * <code>repeated bytes devicetype = 1;</code>
     */
    com.google.protobuf.ByteString getDevicetype(int index);

    /**
     * <code>required bytes mestype = 2;</code>
     */
    boolean hasMestype();
    /**
     * <code>required bytes mestype = 2;</code>
     */
    com.google.protobuf.ByteString getMestype();

    /**
     * <code>required bytes dlgtype = 3;</code>
     */
    boolean hasDlgtype();
    /**
     * <code>required bytes dlgtype = 3;</code>
     */
    com.google.protobuf.ByteString getDlgtype();

    /**
     * <code>optional bytes params = 4;</code>
     */
    boolean hasParams();
    /**
     * <code>optional bytes params = 4;</code>
     */
    com.google.protobuf.ByteString getParams();
  }
  /**
   * Protobuf type {@code DeviceItem}
   */
  public static final class DeviceItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:DeviceItem)
      DeviceItemOrBuilder {
    // Use DeviceItem.newBuilder() to construct.
    private DeviceItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private DeviceItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final DeviceItem defaultInstance;
    public static DeviceItem getDefaultInstance() {
      return defaultInstance;
    }

    public DeviceItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private DeviceItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                devicetype_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000001;
              }
              devicetype_.add(input.readBytes());
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              mestype_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              dlgtype_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000004;
              params_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          devicetype_ = java.util.Collections.unmodifiableList(devicetype_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ReadDeviceCountListReq.internal_static_Proto_DeviceItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ReadDeviceCountListReq.internal_static_Proto_DeviceItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ReadDeviceCountListReq.DeviceItem.class, ReadDeviceCountListReq.DeviceItem.Builder.class);
    }

    public static com.google.protobuf.Parser<DeviceItem> PARSER =
        new com.google.protobuf.AbstractParser<DeviceItem>() {
      public DeviceItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeviceItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<DeviceItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DEVICETYPE_FIELD_NUMBER = 1;
    private java.util.List<com.google.protobuf.ByteString> devicetype_;
    /**
     * <code>repeated bytes devicetype = 1;</code>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getDevicetypeList() {
      return devicetype_;
    }
    /**
     * <code>repeated bytes devicetype = 1;</code>
     */
    public int getDevicetypeCount() {
      return devicetype_.size();
    }
    /**
     * <code>repeated bytes devicetype = 1;</code>
     */
    public com.google.protobuf.ByteString getDevicetype(int index) {
      return devicetype_.get(index);
    }

    public static final int MESTYPE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString mestype_;
    /**
     * <code>required bytes mestype = 2;</code>
     */
    public boolean hasMestype() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes mestype = 2;</code>
     */
    public com.google.protobuf.ByteString getMestype() {
      return mestype_;
    }

    public static final int DLGTYPE_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString dlgtype_;
    /**
     * <code>required bytes dlgtype = 3;</code>
     */
    public boolean hasDlgtype() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes dlgtype = 3;</code>
     */
    public com.google.protobuf.ByteString getDlgtype() {
      return dlgtype_;
    }

    public static final int PARAMS_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString params_;
    /**
     * <code>optional bytes params = 4;</code>
     */
    public boolean hasParams() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes params = 4;</code>
     */
    public com.google.protobuf.ByteString getParams() {
      return params_;
    }

    private void initFields() {
      devicetype_ = java.util.Collections.emptyList();
      mestype_ = com.google.protobuf.ByteString.EMPTY;
      dlgtype_ = com.google.protobuf.ByteString.EMPTY;
      params_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMestype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDlgtype()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < devicetype_.size(); i++) {
        output.writeBytes(1, devicetype_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, mestype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, dlgtype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(4, params_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < devicetype_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(devicetype_.get(i));
        }
        size += dataSize;
        size += 1 * getDevicetypeList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, mestype_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, dlgtype_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, params_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static ReadDeviceCountListReq.DeviceItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReadDeviceCountListReq.DeviceItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReadDeviceCountListReq.DeviceItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ReadDeviceCountListReq.DeviceItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ReadDeviceCountListReq.DeviceItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ReadDeviceCountListReq.DeviceItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static ReadDeviceCountListReq.DeviceItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static ReadDeviceCountListReq.DeviceItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static ReadDeviceCountListReq.DeviceItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static ReadDeviceCountListReq.DeviceItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(ReadDeviceCountListReq.DeviceItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DeviceItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeviceItem)
        ReadDeviceCountListReq.DeviceItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ReadDeviceCountListReq.internal_static_Proto_DeviceItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ReadDeviceCountListReq.internal_static_Proto_DeviceItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ReadDeviceCountListReq.DeviceItem.class, ReadDeviceCountListReq.DeviceItem.Builder.class);
      }

      // Construct using ReadDeviceCountListReq.DeviceItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        devicetype_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        mestype_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        dlgtype_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        params_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ReadDeviceCountListReq.internal_static_Proto_DeviceItem_descriptor;
      }

      public ReadDeviceCountListReq.DeviceItem getDefaultInstanceForType() {
        return ReadDeviceCountListReq.DeviceItem.getDefaultInstance();
      }

      public ReadDeviceCountListReq.DeviceItem build() {
        ReadDeviceCountListReq.DeviceItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ReadDeviceCountListReq.DeviceItem buildPartial() {
        ReadDeviceCountListReq.DeviceItem result = new ReadDeviceCountListReq.DeviceItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          devicetype_ = java.util.Collections.unmodifiableList(devicetype_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.devicetype_ = devicetype_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.mestype_ = mestype_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000002;
        }
        result.dlgtype_ = dlgtype_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000004;
        }
        result.params_ = params_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ReadDeviceCountListReq.DeviceItem) {
          return mergeFrom((ReadDeviceCountListReq.DeviceItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ReadDeviceCountListReq.DeviceItem other) {
        if (other == ReadDeviceCountListReq.DeviceItem.getDefaultInstance()) return this;
        if (!other.devicetype_.isEmpty()) {
          if (devicetype_.isEmpty()) {
            devicetype_ = other.devicetype_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDevicetypeIsMutable();
            devicetype_.addAll(other.devicetype_);
          }
          onChanged();
        }
        if (other.hasMestype()) {
          setMestype(other.getMestype());
        }
        if (other.hasDlgtype()) {
          setDlgtype(other.getDlgtype());
        }
        if (other.hasParams()) {
          setParams(other.getParams());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMestype()) {
          
          return false;
        }
        if (!hasDlgtype()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ReadDeviceCountListReq.DeviceItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ReadDeviceCountListReq.DeviceItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.google.protobuf.ByteString> devicetype_ = java.util.Collections.emptyList();
      private void ensureDevicetypeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          devicetype_ = new java.util.ArrayList<com.google.protobuf.ByteString>(devicetype_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated bytes devicetype = 1;</code>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getDevicetypeList() {
        return java.util.Collections.unmodifiableList(devicetype_);
      }
      /**
       * <code>repeated bytes devicetype = 1;</code>
       */
      public int getDevicetypeCount() {
        return devicetype_.size();
      }
      /**
       * <code>repeated bytes devicetype = 1;</code>
       */
      public com.google.protobuf.ByteString getDevicetype(int index) {
        return devicetype_.get(index);
      }
      /**
       * <code>repeated bytes devicetype = 1;</code>
       */
      public Builder setDevicetype(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDevicetypeIsMutable();
        devicetype_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes devicetype = 1;</code>
       */
      public Builder addDevicetype(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureDevicetypeIsMutable();
        devicetype_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes devicetype = 1;</code>
       */
      public Builder addAllDevicetype(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureDevicetypeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, devicetype_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes devicetype = 1;</code>
       */
      public Builder clearDevicetype() {
        devicetype_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString mestype_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes mestype = 2;</code>
       */
      public boolean hasMestype() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes mestype = 2;</code>
       */
      public com.google.protobuf.ByteString getMestype() {
        return mestype_;
      }
      /**
       * <code>required bytes mestype = 2;</code>
       */
      public Builder setMestype(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        mestype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes mestype = 2;</code>
       */
      public Builder clearMestype() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mestype_ = getDefaultInstance().getMestype();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString dlgtype_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes dlgtype = 3;</code>
       */
      public boolean hasDlgtype() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes dlgtype = 3;</code>
       */
      public com.google.protobuf.ByteString getDlgtype() {
        return dlgtype_;
      }
      /**
       * <code>required bytes dlgtype = 3;</code>
       */
      public Builder setDlgtype(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dlgtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes dlgtype = 3;</code>
       */
      public Builder clearDlgtype() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dlgtype_ = getDefaultInstance().getDlgtype();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString params_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes params = 4;</code>
       */
      public boolean hasParams() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bytes params = 4;</code>
       */
      public com.google.protobuf.ByteString getParams() {
        return params_;
      }
      /**
       * <code>optional bytes params = 4;</code>
       */
      public Builder setParams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        params_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes params = 4;</code>
       */
      public Builder clearParams() {
        bitField0_ = (bitField0_ & ~0x00000008);
        params_ = getDefaultInstance().getParams();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:DeviceItem)
    }

    static {
      defaultInstance = new DeviceItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:DeviceItem)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Proto_DeviceItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Proto_DeviceItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035_ReadDeviceCountListReq.proto\022\005Proto\"R" +
      "\n\nDeviceItem\022\022\n\ndevicetype\030\001 \003(\014\022\017\n\007mest" +
      "ype\030\002 \002(\014\022\017\n\007dlgtype\030\003 \002(\014\022\016\n\006params\030\004 \001" +
      "(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Proto_DeviceItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Proto_DeviceItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Proto_DeviceItem_descriptor,
        new java.lang.String[] { "Devicetype", "Mestype", "Dlgtype", "Params", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
